---
title: "R Notebook"
output: html_document
---
```{r}
library(rTensor)
library(purrr)
library(Rssa)
library(Metrics)

tens3 <- function(s, I, L) {
  require("rTensor")
  v <- as.vector(s)
  N <- length(v)
  J <- N - I - L + 2
  X <- array(NA, c(I, L, J))
  for (i in 1:J) {
    X[, , i] <- outer(1:I, 1:L, function(x, y) s[i + x + y - 2])
  }
  return(as.tensor(X))
}

reconstruct.group3 <- function(X.tens) {
  X <- X.tens@data
  I <- length(X[, 1, 1])
  L <- length(X[1, , 1])
  J <- length(X[1, 1,])
  s <- vector(mode = "numeric", length = I + L + J - 2)
  for (C in 3:(I + L + J)) {
    sum <- 0
    count <- 0
    for (i in 1:(C - 2)) {
      for (l in 1:(C - 1 - i)) {
        if (i <= I && l <= L && C - i - l <= J) {
          sum <- sum + X[i, l, C - i - l]
          count <- count + 1
        }
      }
    }
    s[C - 2] <- sum / count
  }
  return(s)
}

LPA <- function(U1, U2, deg = TRUE) {
  U1.svd <- svd(U1)
  U2.svd <- svd(U2)
  U1.orth <- U1.svd$u[, U1.svd$d > 1e-8]
  U2.orth <- U2.svd$u[, U2.svd$d > 1e-8]
  if (deg)
    acos(min(svd(Conj(t.default(U1.orth)) %*% U2.orth)$d, 1)) * 180 / pi
  else
    acos(min(svd(Conj(t.default(U1.orth)) %*% U2.orth)$d, 1))
}
```

Задача параметров и генерация рядов
```{r}
N <- 23
L <- 12
series.number <- 15
sigma <- 1.5
# set.seed(5)

# rank of the time series
r <- 1
# generating series with ranodm parameters
s <- map(1:series.number, function(x) runif(1, 1, 4) * exp(1:N * 1e-4))
# generating series by hand
# s <- map(1:series.number, function(x) exp(1:N))
s.hankel <- lapply(s, hankel, L)
mat <- reduce(s.hankel, cbind)
u.svd <- svd(mat)
# signal subspace
true.subspace <- u.svd$u[, 1:min(r, N - L + 1), drop = FALSE]
```

```{r}
iterations <- 1000
LPA.mat <- numeric(iterations)
LPA.tens <- numeric(iterations)
mse.mat <- matrix(0, ncol = iterations, nrow = series.number)
mse.tens <- matrix(0, ncol = iterations, nrow = series.number)

pb <- txtProgressBar(max = iterations, style = 3)
for (i in 1:iterations) {
  # noised case
  s.n <- lapply(s, function(x) x + rnorm(N, sd = sigma))
  # noiseless case
  # s.n <- s
  s.n.hankel <- lapply(s.n, hankel, L)
  mat.n <- reduce(s.n.hankel, cbind)
  u.n.svd <- svd(mat.n)
  est.subspace <- u.n.svd$u[, 1:min(r, N - L + 1), drop = FALSE]
  mat.rec <- reconstruct(ssa(s.n, L = L, kind = "mssa"), groups = list(1:r))[[1]]

  s.tens <- fold(mat.n, 1, 2:3, modes = c(L, N - L + 1, series.number))
  capture.output({ h <- rTensor::hosvd(s.tens) })
  tens <- ttl(h$Z[1:r, 1:r, 1:r, drop = FALSE], list(h$U[[1]][, 1:r, drop = FALSE], h$U[[2]][, 1:r, drop = FALSE], h$U[[3]][, 1:r, drop = FALSE]), 1:3)
  # tens <- as.tensor(h$Z@data[1, 1, 1] * (h$U[[1]][, 1] %o% h$U[[2]][, 1] %o% h$U[[3]][, 1]) + h$Z@data[2, 2, 2] * (h$U[[1]][, 2] %o% h$U[[2]][, 2] %o% h$U[[3]][, 2]))
  est.subspace.tens <- unfold(tens, 1, 2:3)@data
  tens.rec <- apply(tens@data, 3, hankel, simplify = FALSE)

  mse.mat[, i] <- map2_dbl(mat.rec, s, mse)
  mse.tens[, i] <- map2_dbl(tens.rec, s, mse)
  LPA.mat[i] <- LPA(est.subspace, true.subspace)
  LPA.tens[i] <- LPA(est.subspace.tens, true.subspace)
  setTxtProgressBar(pb, i)
}
```

Mean LPA for matrix and tensor approaches:
```{r}
mean(LPA.mat)
mean(LPA.tens)
mean(LPA.mat) - mean(LPA.tens)
```

Mean MSE for matrix and tensor approaches:
```{r}
mean(apply(mse.mat, 1, mean))
mean(apply(mse.tens, 1, mean))
mean(apply(mse.mat, 1, mean)) / mean(apply(mse.tens, 1, mean))
# mean(apply(mse.mat, 1, mean)) - mean(apply(mse.tens, 1, mean))
```
