---
title: "Research Cases"
author: "Khromov Nikita"
output: html_document
---

# Setup

```{r setup}
setwd(rprojroot::find_rstudio_root_file())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

library(Rssa)
library(svd)
library(scales)
library(rTensor)
library(ggplot2)
library(dplyr)
library(tidyr)
library(Rcpp)
library(RcppArmadillo)
library(future.apply)
library(progressr)

source(file = "./Source/TSSA.R")
```

```{r enable progressr, eval = FALSE}
# This commands should be executed in R console, not as a chunk
# Otherwise they fail
progressr::handlers(global = TRUE)
progressr::handlers("progress")
```

```{r}
pred_ssa_rec <- function() {
  noise <- rnorm(N, 0, sd)
  x <- signal + noise
  rec <- reconstruct(ssa(x, L = L_ssa), groups = groups_ssa)
  Reduce("+", rec)
}

pred_hossa_rec <- function() {
  noise <- rnorm(N, 0, sd)
  x <- signal + noise
  
  rec <- tens_ssa_reconstruct(
    x,
    # c(I_hossa, L_hossa),
    unlist(L_hossa),
    groups = groups_hossa,
    decomp = "hooi",
    trunc_dims = unlist(td_hossa),
    status = FALSE
  )
  
  Reduce("+", rec)
}

pred_mssa_rec <- function() {
  noise <- rnorm(N * P, 0, sd)
  x <- signal + noise
  # rec <- reconstruct(ssa(x, L = L_mssa, kind = 'mssa'), groups = groups_mssa)
  rec <- cmssa_reconstruct(x, L = L_mssa, groups = groups_mssa)
  Reduce("+", rec)
}

pred_homssa_rec <- function() {
  noise <- rnorm(N * P, 0, sd)
  x <- signal + noise
  
  rec <- tens_mssa_reconstruct(
    x,
    L_homssa,
    groups = groups_homssa,
    groups3 = groups3_homssa,
    decomp = "hooi",
    status = FALSE
  )
  
  Reduce("+", rec)
}
```

```{r}
mse <- function(true, pred) {
  err <- pred - true
  Re(mean(err * Conj(err)))
}

# true is scalar, pred is vector
rmse <- function(true, pred) {
  sqrt(mse(true, pred))
}

# true is vector, pred is matrix with predictions for each parameter in rows
rmse_params_mat <- function(true, pred) {
  apply(cbind(true, pred), 1, \(v) rmse(v[1], v[-1]))
}

# true is nd-array, pred is (n+1)d-array with n+1-mode slices as predictions
rmse_ts_nd <- function(true, pred) {
  sqrt(mean(apply(pred, length(dim(pred)), \(p) mse(true, p))))
}
```

```{r}
calc_errors <- function(R, pred_func, err_func, signal, progbar, seed = 5) {
  with(plan(multisession), {
    batch_recs <- function(R) {
      # p <- progressor(R)
      future_replicate(R, {
        # p()
        progbar()
        pred_func()
      }, simplify = "array", future.seed = seed)
    }
    if (sd == 0)
      recs <- batch_recs(2) # don't need R because no noise present. Set to 2, because with 1 will be simplified
    else
      recs <- batch_recs(R)
  })
  
  return(err_func(signal, recs))
}

# params_grid_list: list with the parameter names as names and vectors of the parameters values as values
calc_errors_by_params <- function(params_grid_list, R, comp_func, err_func, signal, seed = 5) {
  params_grid <- expand.grid(params_grid_list)
  results <- params_grid
  results$error <- numeric(nrow(params_grid))
  q <- progressor(nrow(params_grid) * R)
  # q <- progressor(nrow(params_grid))
  for (i in seq(nrow(params_grid))) {
    # print(paste0(names(params_grid), " = ", params_grid[i,], collapse = ", "))
    list2env(params_grid[i,], envir = parent.frame())
    results[i,]$error <- calc_errors(R, comp_func, err_func, signal, q, seed)
    # q()
  }
  return(results)
}
```

```{r}
polynom_eval <- function(coefs, x) {
  powers <- outer(x, seq_along(coefs) - 1, FUN = "^")
  result <- powers %*% coefs
  
  return(as.vector(result))
}

# If parameters are matrices, then a multivariate series will be constructed.
# In this parameters matrices columns correspond to summands and rows to channels
# This means, if you want to increase number of ts in a sum, you grow columns,
# and if you want to add a channel to an mv ts, you grow rows
# The result is either a 1d ts, or a matrix, where each column is a 1d ts -- channel.
construct_periodics <- function(N,
                                ampl,
                                rate,
                                freq,
                                phase,
                                complex = TRUE,
                                poly_ampl_coefs = NULL,
                                from = 0,
                                by = 1) {
  if (any(c(length(ampl), length(rate), length(freq)) != length(phase))) {
    stop("Amplitudes, rates, frequencies and phases all must have the same length")
  }
  if (all(is.matrix(ampl), is.matrix(rate), is.matrix(freq), is.matrix(phase))) {
    if (any(c(dim(ampl), dim(rate), dim(freq)) != dim(phase))) {
      stop("Amplitudes, rates, frequencies and phases all must have the same dimensions")
    }
    if (is.null(poly_ampl_coefs)) {
      poly_ampl_coefs <- 1 %o% rep(1, nrow(ampl)) %o% rep(1, ncol(ampl))
    } else {
      stopifnot(
                is.array(poly_ampl_coefs) && 
                length(dim(poly_ampl_coefs)) - 1 == length(dim(ampl)) &&
                all(dim(poly_ampl_coefs)[-1] == dim(ampl))
               )
    }
  } else {
    if (any(is.matrix(ampl), is.matrix(rate), is.matrix(freq), is.matrix(phase))) {
      stop("All parameters should be either matrices, or vectors at the same time")
    }

    if (is.null(poly_ampl_coefs)) {
      poly_ampl_coefs <- 1 %o% rep(1, length(ampl))
    } else {
      stopifnot(
                is.matrix(poly_ampl_coefs) && 
                length(dim(poly_ampl_coefs) == 2) &&
                dim(poly_ampl_coefs)[2] == length(ampl)
               )
    }
  }
  
  if (complex) {
    period_f <- exp
    unit <- 1i
  } else {
    period_f <- cos
    unit <- 1
  }
  N_ones <- rep(1, N)
  ts_range <- seq(from = from, length.out = N, by = by)
  poly_ampl <- apply(poly_ampl_coefs, 2:length(dim(poly_ampl_coefs)), polynom_eval, x=ts_range)
  ts_arr <- poly_ampl * (N_ones %o% ampl) * (N_ones %o% exp(rate)) *
    period_f(N_ones %o% phase + 2 * pi * unit * ts_range %o% freq)

  apply(ts_arr, 1:(length(dim(ts_arr)) - 1), sum)
}

calc_rank <- function(ampl, rate, freq, phase, complex = TRUE, poly_ampl_coefs = NULL, tol = 1e-6) {
  if (any(c(length(ampl), length(rate), length(freq)) != length(phase)))
    stop("Amplitudes, rates, frequencies and phases all must have the same length")
  if (is.null(poly_ampl_coefs))
    pac_rank <- rep(1, length(ampl))
  else
    pac_rank <- apply(poly_ampl_coefs, 2:length(dim(poly_ampl_coefs)), function(v) max(which(v != 0)))
  fr_df <- data.frame(freq = freq, rate = rate, pac = pac_rank)
  fr_unique <- fr_df |> group_by(freq, rate) |> summarise(pac = max(pac))
  (2 - complex) *
    (sum(ampl != 0) + sum(fr_unique$pac) - length(ampl)) - sum(abs(fr_unique[,1] - 0.5) < tol)
}

# Assumes all amplitudes are non-zero
# TODO: This is totally wrong and must not be used
calc_rank3 <- function(rate, freq, phase, complex = TRUE, tol = 1e-6) {
  if (any(c(length(ampl), length(rate), length(freq)) != length(phase)))
    stop("Amplitudes, rates, frequencies and phases all must have the same length")
  f_unique <- nrow(unique(freq))
  r_unique <- nrow(unique(rate))
  p_unique <- nrow(unique(phase))
  return(min(ncol(rate), f_unique + r_unique + p_unique - 2))
}
```


```{r}
print_errors <- function(err_df) {
  err_df |> mutate(zapped_error = zapsmall(error)) |> group_by(sd) |> arrange(zapped_error, L_ssa, .by_group = TRUE)
}

print_errors_m <- function(err_df) {
  err_df |> mutate(zapped_error = zapsmall(error)) |> group_by(sd) |> arrange(zapped_error, L_mssa, .by_group = TRUE)
}

summarise_errors <- function(err_df) {
  err_df |> mutate(zapped_error = zapsmall(error)) |> group_by(sd) |> summarise(
    best = min(zapped_error),
    best_L = L[which.min(zapped_error)],
    avg = mean(zapped_error),
    worst = max(zapped_error)
  )
}
```



# Two periodics case
## Parameters for 1d series
```{r}
# no rates
rates.true <- c(0, 0)
rates_case <- "_nr"
# small equal rated
# rates.true <- c(-0.01, -0.01)
# rates_case <- "_ser"
# large equal rates
# rates.true <- c(-0.02, -0.02)
# rates_case <- "_ler"
# different rates
# rates.true <- c(-0.01, -0.02)
# rates_case <- "_dr"

# no freqs
# freqs.true <- c(0, 0)
# freqs_case <- "_nf"
# different freqs
freqs.true <- c(0.2, 0.22)
freqs_case <- "_df"
# close different freqs
# freqs.true <- c(0.02, 0.0205)
# freqs_case <- "_cdf"

# equal amplitudes
A <- c(1, 1)
A_case <- "_ea"
# different amplitudes
# A <- c(1, 2)
# A_case <- "_da"

# equal phases
phases.true <- c(0, 0)
phases_case <- "_ep"
# different phases
# phases.true <- c(0, pi / 3)
# phases_case <- "_dp"

# complex.signal <- TRUE
# complex_case <- "_c" # complex
complex.signal <- FALSE
complex_case <- "_r" # real

# N <- 25
# n_case <- ""
N <- 100
n_case <- "_long"
```


## Parameters for mv series (P = 2)
```{r}
P <- 2
P_case = ""

# no rates
# rates.true <- matrix(c(0, 0, 0, 0), nrow = P)
# rates_case <- "_nr"
# small equal rated
# rates.true <- matrix(c(-0.01, -0.01, -0.01, -0.01), nrow = P)
# rates_case <- "_ser"
# large equal rates
# rates.true <- matrix(c(-0.02, -0.02, -0.02, -0.02), nrow = P)
# rates_case <- "_ler"
# different by summands rates
# rates.true <- matrix(c(-0.01, -0.01, -0.02, -0.02), nrow = P)
# rates_case <- "_dsr"
# different by time series rates
rates.true <- matrix(c(-0.01, -0.02, -0.01, -0.02), nrow = P)
rates_case <- "_dtr"
# different rates
# rates.true <- matrix(c(-0.01, -0.02, -0.015, -0.025), nrow = P)
# rates_case <- "_dr"

# no freqs
# freqs.true <- matrix(c(0, 0, 0, 0), nrow = P)
# freqs_case <- "_nf"
# different by summands freqs
# freqs.true <- matrix(c(0.2, 0.2, 0.22, 0.22), nrow = P)
# freqs_case <- "_dsf"
# different by time series freqs
freqs.true <- matrix(c(0.2, 0.22, 0.2, 0.22), nrow = P)
freqs_case <- "_dtf"
# different freqs
# freqs.true <- matrix(c(0.2, 0.22, 0.18, 0.24), nrow = P)
# freqs_case <- "_df"
# close different by summands freqs
# freqs.true <- matrix(c(0.02, 0.02, 0.0205, 0.0205), nrow = P)
# freqs_case <- "_cdsf"

# equal amplitudes
A <- matrix(c(1, 1, 1, 1), nrow = P)
A_case <- "_ea"
# different by summands amplitudes 
# A <- matrix(c(1, 2, 1, 2), nrow = P)
# A_case <- "_dsa"
# different by summands, proportional by ts amplitudes 
# A <- matrix(c(1, 2, 3, 6), nrow = P)
# A_case <- "_dspta"
# different amplitudes
# A <- matrix(c(1, 2, 1.5, 2.5), nrow = P)
# A_case <- "_da"

# equal phases
phases.true <- matrix(c(0, 0, 0, 0), nrow = P)
phases_case <- "_ep"
# different by time series phases
# phases.true <- matrix(c(0, pi / 3, 0, pi / 3), nrow = P)
# phases_case <- "_dtp"

# complex.signal <- TRUE
# complex_case <- "_c" # complex
complex.signal <- FALSE
complex_case <- "_r" # real

N <- 25
n_case <- ""
# N <- 100
# n_case <- "_long"
```


## Parameters for mv series (P = 4)
```{r}
P <- 4
P_case <- "_c4"

# no rates
rates.true <- matrix(rep(0, P * 2), nrow = P)
rates_case <- "_nr"
# small equal rated
# rates.true <- matrix(c(-0.01, -0.01, -0.01, -0.01), nrow = P)
# rates_case <- "_ser"
# large equal rates
# rates.true <- matrix(c(-0.02, -0.02, -0.02, -0.02), nrow = P)
# rates_case <- "_ler"
# different by summands rates
# rates.true <- matrix(c(-0.01, -0.01, -0.02, -0.02), nrow = P)
# rates_case <- "_dsr"
# different by time series rates
# rates.true <- matrix(rep(c(-0.01, -0.02), P * 2), nrow = P)
# rates_case <- "_dtr"
# rates.true <- matrix(rep(c(-0.01, -0.02, -0.03, -0.01), P), nrow = P)
# rates_case <- "_dtr"
# rates.true <- matrix(rep(c(-0.01, -0.02, -0.03, -0.04), P), nrow = P)
# rates_case <- "_dtr"
# different rates
# rates.true <- matrix(c(-0.01, -0.02, -0.015, -0.025), nrow = P)
# rates_case <- "_dr"

# no freqs
# freqs.true <- matrix(rep(0, P * 4), nrow = P)
# freqs_case <- "_nf"
# all freqs equal
# freqs.true <- matrix(rep(0.2, P * 2), nrow = P)
# freqs_case <- "_ef"
# different by summands freqs
freqs.true <- matrix(rep(c(0.2, 0.22), each = P), nrow = P)
freqs_case <- "_dsf"
# different by time series freqs
# freqs.true <- matrix(rep(c(0.2, 0.22), P * 2), nrow = P)
# freqs_case <- "_dtf"
# freqs.true <- matrix(rep(c(0.2, 0.22, 0.24, 0.2), P), nrow = P)
# freqs_case <- "_dtf"
# freqs.true <- matrix(rep(c(0.2, 0.22, 0.24, 0.26), P), nrow = P)
# freqs_case <- "_dtf"
# different freqs
# freqs.true <- matrix(c(0.2, 0.22, 0.18, 0.24), nrow = P)
# freqs_case <- "_df"
# close different by summands freqs
# freqs.true <- matrix(c(0.02, 0.02, 0.0205, 0.0205), nrow = P)
# freqs_case <- "_cdsf"

# equal amplitudes
A <- matrix(rep(1, P * 2), nrow = P)
A_case <- "_ea"
# different by summands amplitudes 
# A <- matrix(c(1, 2, 1, 2), nrow = P)
# A_case <- "_dsa"
# different by summands, proportional by ts amplitudes 
# A <- matrix(c(1, 2, 3, 6), nrow = P)
# A_case <- "_dspta"
# different amplitudes
# A <- matrix(c(1, 2, 1.5, 2.5, 1.8, 2.3, 2.8, 1.3), nrow = P)
# A_case <- "_da"

# equal phases
# phases.true <- matrix(rep(0, P * 2), nrow = P)
# phases_case <- "_ep"
phases.true <- matrix(rep(0, P * 2), nrow = P)
phases_case <- "_ep"
# different by time series phases
# phases.true <- matrix(c(0, pi / 3, 0, pi / 3), nrow = P)
# phases_case <- "_dtp"

# complex.signal <- TRUE
# complex_case <- "_c" # complex
complex.signal <- FALSE
complex_case <- "_r" # real

N <- 25
n_case <- ""
# N <- 100
# n_case <- "_long"
```

## Parameters for P from 2 to 20 with one periodic
```{r}
set.seed(5)

P <- 2
P_case <- "_c2"
# P <- 4
# P_case <- "_c4"
# P <- 8
# P_case <- "_c8"
# P <- 12
# P_case <- "_c12"
# P <- 16
# P_case <- "_c16"
# P <- 20
# P_case <- "_c20"

rates.true <- matrix(rep(0, P), nrow = P)
rates_case <- "_nr"

freqs.true <- matrix(rep(0.2, P), nrow = P)
freqs_case <- "_ef"

A <- matrix(rnorm(P), nrow = P)
A_case <- "_da"

# poly.true <- 1 %o% rep(1, P) %o% 1
# poly_case <- ""
poly.true <- c(1, 1) * matrix(runif(2 * P, 0.5, 2), nrow = 2) %o% 1
poly_case <- "p1"

phases.true <- matrix(rep(0, P), nrow = P)
phases_case <- "_ep"

# complex.signal <- TRUE
# complex_case <- "_c" # complex
complex.signal <- FALSE
complex_case <- "_r" # real

N <- 25
n_case <- ""
# N <- 100
# n_case <- "_long"
```


## Constructing Signal

```{r}
full_case <- paste0(n_case, P_case, rates_case, freqs_case, A_case, poly_case, phases_case, complex_case)
max.r <- calc_rank(A, rates.true, freqs.true, phases.true, complex.signal, poly.true)

stopifnot(N > max.r * 2 + 1)
signal <- construct_periodics(N, A, rates.true, freqs.true, phases.true, complex.signal, poly.true)
```



## Parameters grid for 1d case
```{r}
if (!is.matrix(signal)) {
groups_ssa <- list(1:max.r)

if (n_case == "") {
  Ls_ssa <- seq(from = max.r + 1,
                to = (N + 1) %/% 2,
                by = 1)
} else {
  Ls_ssa <- seq(from = max.r + 1,
                to = (N + 1) %/% 2,
                by = 5)
}


groups_hossa <- list(1:max.r)
trunc_dims <- list(1, 1:3)

# I >= L >= J
if (n_case == "") {
  Is_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 1)
  Ls_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 1)
} else {
  Is_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 5)
  Ls_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 5)
}
correct.dims <- which(outer(Is_tmp, Ls_tmp, (\(i, l) ifelse((i >= l) &
                                                      (N - i - l + 2 > max.r) &
                                                      (N - i - l + 2 <= l), TRUE, FALSE
))), arr.ind = TRUE)

len.out <- nrow(correct.dims)

tens.dims <- matrix(ncol = 3, nrow = len.out)
colnames(tens.dims) <- c("I", "L", "J")
tens.dims[, "I"] <- Is_tmp[correct.dims[, 1]]
tens.dims[, "L"] <- Ls_tmp[correct.dims[, 2]]
tens.dims[, "J"] <- N - tens.dims[, "I"] - tens.dims[, "L"] + 2

tens.dims <- tens.dims[order(tens.dims[, 1], tens.dims[, 2], decreasing = TRUE), ]
tens.dims_list <- apply(tens.dims, 1, \(v) v[1:2], simplify = list)


sds <- seq(0, 0.6, by = 0.2)

params_grid_ssa <- list(sd = sds, L_ssa = Ls_ssa)
params_grid_hossa <- list(sd = sds,
                          td_hossa =  trunc_dims,
                          L_hossa = tens.dims_list)
}
```

## Parameters grid for mv case
```{r}
if (is.matrix(signal)) {
groups_mssa <- list(1:max.r)

if (n_case == "") {
  Ls_mssa <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 2)
  Ls_homssa = seq(from = max.r + 1,
                to = (N + 1) %/% 2,
                by = 2)
} else {
  Ls_mssa <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 10)
  Ls_homssa = seq(from = max.r + 1,
                to = (N + 1) %/% 2,
                by = 10)
}

max.r3 <- tens_mssa_decompose(signal, N %/% 2)$Z@data |> zapsmall() |> apply(3, \(x) any(x != 0)) |> sum()
groups_homssa <- list(1:max.r)
groups3_homssa <- list(1:max.r3)

sds <- seq(0, 0.6, by = 0.2)

params_grid_ssa <- list(sd = sds, L_mssa = Ls_mssa)
params_grid_hossa <- list(sd = sds,
                          L_homssa = Ls_homssa)
}
```

```{r}
R <- 500

if (is.matrix(signal)) {
  ssa_err <- calc_errors_by_params(params_grid_ssa, R, pred_mssa_rec, rmse_ts_nd, signal, seed = 5)
  tssa_err <- calc_errors_by_params(params_grid_hossa, R, pred_homssa_rec, rmse_ts_nd, signal, seed = 5)
  save(ssa_err, tssa_err, file = paste0("./Research/comp_results/cases_errors/one_periodic_mv", full_case, ".RData"))
} else {
  ssa_err <- calc_errors_by_params(params_grid_ssa, R, pred_ssa_rec, rmse_ts_nd, signal, seed = 5)
  tssa_err <- calc_errors_by_params(params_grid_hossa, R, pred_hossa_rec, rmse_ts_nd, signal, seed = 5)
  save(ssa_err, tssa_err, file = paste0("./Research/comp_results/cases_errors/one_periodic", full_case, ".RData"))
}

# if (is.matrix(signal)) {
#   ssa_err <- calc_errors_by_params(params_grid_ssa, R, pred_mssa_rec, rmse_ts_nd, signal, seed = 5)
#   tssa_err <- calc_errors_by_params(params_grid_hossa, R, pred_homssa_rec, rmse_ts_nd, signal, seed = 5)
#   save(ssa_err, tssa_err, file = paste0("./Research/comp_results/cases_errors/two_periodics_mv", full_case, ".RData"))
# } else {
#   ssa_err <- calc_errors_by_params(params_grid_ssa, R, pred_ssa_rec, rmse_ts_nd, signal, seed = 5)
#   tssa_err <- calc_errors_by_params(params_grid_hossa, R, pred_hossa_rec, rmse_ts_nd, signal, seed = 5)
#   save(ssa_err, tssa_err, file = paste0("./Research/comp_results/cases_errors/two_periodics", full_case, ".RData"))
# }
```

# Results
```{r}
# load()
```


```{r}
if (is.matrix(signal)) {
  print_errors_m(ssa_err)
} else {
  print_errors(ssa_err)
}
(ssa_err_summ <- summarise_errors(rename(ssa_err, L = L_mssa)))
```

```{r}
if (is.matrix(signal)) {
  print_errors_m(tssa_err)
} else {
  print_errors(tssa_err)
}
(tssa_err_summ <- summarise_errors(rename(tssa_err, L = L_homssa)))
```


```{r}
((ssa_err_summ[-1, 2] - tssa_err_summ[-1, 2]) / ssa_err_summ[-1, 1]) |> rename(err_diff = best)
```
