---
title: ""
output: html_document
---
```{r, echo = FALSE, results = FALSE, message = FALSE}
tssa3 <- function(s, I = (length(s) + 2) %/% 3, L = I) {
  X <- tens3(s, I, L)
  result <- list()
  result$X <- X
  result$modes <- list(I = I, L = L, J = length(s)-I-L+2)
  result$hosvd <- hosvd(X)
  return(result)
}

tens3 <- function(s, I, L) {
  require("rTensor")
  v <- as.vector(s)
  N <- length(v)
  J <- N - I - L + 2
  X <- outer(1:L, 1:J, function(l, j) l + j) |> outer(1:I, function(lj, i) s[lj + i - 2])
  return(as.tensor(X))
}

# diagonal averaging i + j + k = const, const = 3:(I+L+J)
reconstruct.group3 <- function (X.tens) {
  stopifnot(is(X.tens, "Tensor"))
  X <- X.tens@data
  I <- length(X[,1,1])
  L <- length(X[1,,1])
  J <- length(X[1,1,])
  s <- vector(mode = "numeric", length = I + L + J - 2)
  for (C in 3:(I+L+J)){
    sum <- 0
    count <- 0
    for (i in 1:(C - 2)){
      for (l in 1:(C - 1 - i)){
        if (i <= I && l <= L && C - i - l <= J) {
          sum <- sum + X[i, l, C - i - l]
          count <- count + 1
        }
      }
    }
    s[C - 2] <- sum / count
  }
  return(s)
}

make.group <- function (hosvd, group) {
  ttl(hosvd$Z[group,group,group,drop=FALSE], list(
    as.matrix(hosvd$U[[1]][,group]),
    as.matrix(hosvd$U[[2]][,group]),
    as.matrix(hosvd$U[[3]][,group])),
    1:3)
}

t3.reconstruct <- function(p, groups) {
  stopifnot(is.list(groups))
  lapply(lapply(groups, make.group, hosvd = p$hosvd), reconstruct.group3)
}

library(Rssa)
library(Metrics)
```

```{r}
N <- 71
sigma <- 5
s <- 30 * cos(2 * pi * 1:N / 12)
s.noise <- rnorm(N, 0, sigma)
res.ssa <- list(0, 0, 0, 0)
names(res.ssa) <- c(12, 24, 30, 36)
for (L in c(12, 24, 30, 36)) {
  t.s <- ssa(s + s.noise, L = L)
  t.r <- reconstruct(t.s, list(1:2))
  res.ssa[[as.character(L)]] <- mse(t.r[[1]], s)
}

res.tssa <- list(0, 0, 0, 0, 0, 0)
names(res.tssa) <- c("12x12", "12x24", "12x30", "24x24", "24x30", "30x36")
pairs <- list(c(12, 12), c(12, 24), c(12, 30), c(24, 24), c(24, 30), c(30, 36))
for (IL in pairs) {
  t.t <- tssa3((s + s.noise)[-N], IL[1], IL[2])
  t.tr <- t3.reconstruct(t.t, list(1:2))
  res.tssa[[paste(as.character(IL[1]), as.character(IL[2]), sep="x")]] <- mse(t.tr[[1]], s[-N])
}

save("s", "s.noise", "t.r", "t.tr", "res.ssa", "res.tssa", file = "compare.rdata")
```

```{r}
N <- 71
sigma <- 5
s.cos <- 10 * cos(2 * pi * 1:N / 12)
s.const <- 20
s <- s.cos + s.const
res.ssa <- list(c(0, 0), c(0, 0), c(0, 0), c(0, 0))
names(res.ssa) <- c(12, 24, 30, 36)
for (L in c(12, 24, 30, 36)) {
  t.s <- ssa(s, L = L)
  t.r <- reconstruct(t.s, list(1, 2:3))
  res.ssa[[as.character(L)]] <- c(mse(t.r[[1]], s.const), mse(t.r[[2]], s.cos))
}

res.tssa <- list(c(0, 0), c(0, 0), c(0, 0), c(0, 0), c(0, 0), c(0, 0))
names(res.tssa) <- c("12x12", "12x24", "12x30", "24x24", "24x30", "30x36")
pairs <- list(c(12, 12), c(12, 24), c(12, 30), c(24, 24), c(24, 30), c(30, 36))
for (IL in pairs) {
  t.t <- tssa3((s)[-N], I = IL[1], L = IL[2])
  t.tr <- t3.reconstruct(t.t, list(1, 2:3))
  res.tssa[[paste(as.character(IL[1]), as.character(IL[2]), sep="x")]] <- c(mse(t.tr[[1]], s.const[-N]), mse(t.tr[[2]], s.cos[-N]))
}

save("s.cos", "s.const", "s", "t.r", "t.tr", "res.ssa", "res.tssa", file = "separability.rdata")
```
