---
title: "Parameters estimation via HOSVD"
output: html_document
---
```{r setup, include=FALSE}
library(Rssa)
library(rTensor)
library(ggplot2)
library(gridExtra)
library(factoextra)
library(dplyr)
library(tidyr)
library(waldo)
```

```{r tensorization}
tens3 <- function(s, I, L, kind = c("HO-SSA", "HO-MSSA")) {
  require("rTensor")
  if (identical(kind[1], "HO-SSA")) {
    N <- length(s)
    J <- N - I - L + 2
    X <- outer(1:I, 1:L, `+`) |>
      outer(1:J, function(il, j)
        s[il + j - 2]) |> as.tensor()
  }
  else if (identical(kind[1], "HO-MSSA")) {
    if (missing(L))
      L <- I
    N <- nrow(s)
    K <- N - L + 1
    Q <- ncol(s)
    X <- apply(s, 2, Rssa::hankel, L = L, simplify = FALSE) |>
      Reduce(cbind, x = _) |>
      rTensor::fold(1, 2:3, modes = c(L, K, Q))
  }
  return(X)
}

reconstruct.group3 <- function(X.tens) {
  stopifnot(is(X.tens, "Tensor"))
  X <- X.tens@data
  I <- length(X[, 1, 1])
  L <- length(X[1, , 1])
  J <- length(X[1, 1,])
  s <- vector(mode = "numeric", length = I + L + J - 2)
  for (C in 3:(I + L + J)) {
    sum <- 0
    count <- 0
    for (i in 1:(C - 2)) {
      for (l in 1:(C - 1 - i)) {
        if (i <= I && l <= L && C - i - l <= J) {
          sum <- sum + X[i, l, C - i - l]
          count <- count + 1
        }
      }
    }
    s[C - 2] <- sum / count
  }
  return(s)
}
```

```{r hosvd-mod}
fnorm_complex <- function(x) {
  sqrt(sum(abs(x) ^ 2))
}

setMethod("fnorm_complex", "Tensor", function(tnsr) {
  sqrt(sum(abs(tnsr@data) ^ 2))
})

hosvd_mod <- function(tnsr, ranks = NULL, status = TRUE) 
{
    stopifnot(is(tnsr, "Tensor"))
    if (sum(ranks <= 0) != 0) 
        stop("ranks must be positive")
    if (all(tnsr@data == 0)) 
        stop("Zero tensor detected")
    num_modes <- tnsr@num_modes
    if (is.null(ranks)) {
        ranks <- tnsr@modes
    }
    else {
        if (sum(ranks > tnsr@modes) != 0) 
            stop("ranks must be smaller than the corresponding mode")
    }
    if (status) {
      pb <- txtProgressBar(min = 0, max = num_modes, style = 3)
      U_list <- vector("list", num_modes)
      for (m in 1:num_modes) {
        temp_mat <- rs_unfold(tnsr, m = m)@data
        U_list[[m]] <- svd(temp_mat, nu = ranks[m])$u
        setTxtProgressBar(pb, m)
      }
      close(pb)
    }
    else {
      U_list <- vector("list", num_modes)
      for (m in 1:num_modes) {
        temp_mat <- rs_unfold(tnsr, m = m)@data
        U_list[[m]] <- svd(temp_mat, nu = ranks[m])$u
      }
    }
    Z <- ttl(tnsr, lapply(U_list, (\(.) Conj(t(.)))), ms = 1:num_modes)
    est <- ttl(Z, U_list, ms = 1:num_modes)
    resid <- fnorm_complex(est - tnsr)
    list(Z = Z, U = U_list, est = est, fnorm_resid = resid)
}

tucker_mod <- function(tnsr, ranks = NULL, max_iter = 25, tol = 1e-05, status = TRUE) 
{
    stopifnot(is(tnsr, "Tensor"))
    if (is.null(ranks)) 
        stop("ranks must be specified")
    if (sum(ranks > tnsr@modes) != 0) 
        stop("ranks must be smaller than the corresponding mode")
    if (sum(ranks <= 0) != 0) 
        stop("ranks must be positive")
    if (all(tnsr@data == 0)) 
        stop("Zero tensor detected")
    num_modes <- tnsr@num_modes
    U_list <- vector("list", num_modes)
    for (m in 1:num_modes) {
        temp_mat <- rs_unfold(tnsr, m = m)@data
        U_list[[m]] <- svd(temp_mat, nu = ranks[m])$u
    }
    tnsr_norm <- fnorm_complex(tnsr)
    curr_iter <- 1
    converged <- FALSE
    fnorm_resid <- rep(0, max_iter)
    CHECK_CONV <- function(Z, U_list) {
        est <- ttl(Z, U_list, ms = 1:num_modes)
        curr_resid <- fnorm_complex(tnsr - est)
        fnorm_resid[curr_iter] <<- curr_resid
        if (curr_iter == 1) 
            return(FALSE)
        if (abs(curr_resid - fnorm_resid[curr_iter - 1])/tnsr_norm < 
            tol) 
            return(TRUE)
        else {
            return(FALSE)
        }
    }
    if (status) {
      pb <- txtProgressBar(min = 0, max = max_iter, style = 3)
      while ((curr_iter < max_iter) && (!converged)) {
        setTxtProgressBar(pb, curr_iter)
        modes <- tnsr@modes
        modes_seq <- 1:num_modes
        for (m in modes_seq) {
          X <- ttl(tnsr, lapply(U_list[-m], (\(.) Conj(t(.)))), ms = modes_seq[-m])
          U_list[[m]] <- svd(rs_unfold(X, m = m)@data, nu = ranks[m])$u
        }
        Z <- ttm(X, mat = Conj(t(U_list[[num_modes]])), m = num_modes)
        if (CHECK_CONV(Z, U_list)) {
          converged <- TRUE
          setTxtProgressBar(pb, max_iter)
        }
        else {
          curr_iter <- curr_iter + 1
        }
      }
      close(pb)
    }
    else {
      while ((curr_iter < max_iter) && (!converged)) {
        modes <- tnsr@modes
        modes_seq <- 1:num_modes
        for (m in modes_seq) {
          X <- ttl(tnsr, lapply(U_list[-m], (\(.) Conj(t(.)))), ms = modes_seq[-m])
          U_list[[m]] <- svd(rs_unfold(X, m = m)@data, nu = ranks[m])$u
        }
        Z <- ttm(X, mat = Conj(t(U_list[[num_modes]])), m = num_modes)
        if (CHECK_CONV(Z, U_list)) {
          converged <- TRUE
        }
        else {
          curr_iter <- curr_iter + 1
        }
      }
    }
    
    fnorm_resid <- fnorm_resid[fnorm_resid != 0]
    norm_percent <- (1 - (tail(fnorm_resid, 1)/tnsr_norm)) * 
        100
    est <- ttl(Z, U_list, ms = 1:num_modes)
    invisible(list(Z = Z, U = U_list, conv = converged, est = est, 
        norm_percent = norm_percent, fnorm_resid = tail(fnorm_resid, 
            1), all_resids = fnorm_resid))
}
```

```{r test-hosvd-mod}
X.test <- rTensor::rand_tensor()
cat("Real example:\n")
waldo::compare(hosvd(X.test), hosvd_mod(X.test))

cat("\nComplex example:\n")
X.test.complex <- tens3(exp(1:10 * 1i), 3, 4)
waldo::compare(hosvd(X.test.complex), hosvd_mod(X.test.complex))
```

```{r test-hooi-mod}
X.test <- rTensor::rand_tensor()
cat("Real example:\n")
waldo::compare(tucker(X.test, c(3, 3, 3)), tucker_mod(X.test, c(3, 3, 3)))

cat("\nComplex example:\n1. Package function\n")
X.test.complex <- tens3(exp(1:10 * 1i), 3, 4)
try(tucker(X.test.complex, c(3, 3, 3)))
cat("2. Modified function\n")
try(tucker_mod(X.test.complex, c(3, 3, 3)))
cat("\nFnorm of the residual for modified function:\n")
tucker_mod(X.test.complex, c(1, 1, 1), status = FALSE)$fnorm_resid
```

```{r tensor-based-esprit}
tens_esprit <- function(s, I, L, groups, kind = c("HO-SSA", "HO-MSSA"), est_dim = 3, 
                        status = TRUE, qrtol = 1e-07) {
  if (identical(kind[1], "HO-SSA"))
    H <- tens3(s, I, L)
  else if (identical(kind[1], "HO-MSSA"))
  {
    if (missing(L))
      L <- I
    H <- tens3(s, L, kind = "HO-MSSA")
  }
  max_rank <- max(sapply(groups, max))
  H.hooi <- tucker_mod(H, rep(max_rank, 3), status = status)
  estimates <- list()
  for (i in seq(groups)) {
    U <- H.hooi$U[[est_dim]][, groups[[i]], drop = FALSE]
    Z <- qr.solve(U[-nrow(U), ], U[-1, ], qrtol)
    poles <- eigen(Z, only.values = TRUE)$values
    estimates[[i]] <- list(
      poles = poles,
      rates = Re(log(poles)),
      frequencies = Im(log(poles)) / 2 / pi
    )
  }
  estimates
}
```

```{r complex-noise-generator}
CCSWGN <- function(n, mean = 0, sd = 1) {
  rnorm(n, mean = Re(mean), sd = sd / sqrt(2)) + 1i * rnorm(n, mean = Im(mean), sd = sd / sqrt(2))
}
```

```{r rrmse}
rrmse <- function(true, estimate) {
  100 * sqrt(mean(abs(true - estimate)^2)) / abs(true)
}
```


```{r plot-and-save}
plot.save <- function(plt, name, format, ..., save = TRUE) {
  print(plt)
  if (save){
    format(name, ...)
    print(plt)
    dev.off()
  }
}
save = FALSE
```

```{r test-1d-ssa-esprit-no-noise}
n <- 25
x <- exp((-0.01 + 2i * pi * 0.2) * 0:(n - 1)) + exp((-0.02 + 2i * pi * 0.22) * 0:(n - 1))
L <- 15
x.ssa <- ssa(x, L = L) 
pars <- parestimate(x.ssa, groups = list(1:2))
cat("Rates:\n", pars$rates, "\nFrequencies:\n", pars$frequencies)
```
```{r test-1d-tens-esprit-no-noise}
n <- 25
x <- exp((-0.01 + 2i * pi * 0.2) * 0:(n - 1)) + exp((-0.02 + 2i * pi * 0.22) * 0:(n - 1))
I <- 14; L <- 8
pars <- tens_esprit(x, I, L, groups = list(1:2), status = FALSE)
cat("Rates:\n", pars[[1]]$rates, "\nFrequencies:\n", pars[[1]]$frequencies)
```

```{r test-1d-esprit-noise, results='hide'}
set.seed(10)
n <- 25
L <- 15
I <- 14; L.tens <- 8
rates.true <- c(-0.01, -0.02)
freqs.true <- c(0.2, 0.22)
signal <- exp((rates.true[1] + 2i * pi * freqs.true[1]) * 0:(n - 1)) +
  exp((rates.true[2] + 2i * pi * freqs.true[2]) * 0:(n - 1))
sd <- 0.04
R <- 1000

pars.ssa <- list(
  rate1 = numeric(R),
  rate2 = numeric(R),
  freq1 = numeric(R),
  freq2 = numeric(R)
)
pars.tssa <- list(
  rate1 = numeric(R),
  rate2 = numeric(R),
  freq1 = numeric(R),
  freq2 = numeric(R)
)
pb <- txtProgressBar(max = R, style = 3)
for (i in seq(R)) {
  noise <- CCSWGN(n, mean = 0, sd = sd)
  x <- signal + noise
  x.ssa <- ssa(x, L = L)
  par.ssa <- parestimate(x.ssa, groups = list(1:2))
  pars.ssa$rate1[i] <- max(par.ssa$rates[1], par.ssa$rates[2])
  pars.ssa$rate2[i] <- min(par.ssa$rates[1], par.ssa$rates[2])
  pars.ssa$freq1[i] <- min(par.ssa$frequencies[1], par.ssa$frequencies[2])
  pars.ssa$freq2[i] <- max(par.ssa$frequencies[1], par.ssa$frequencies[2])
  par.tssa <- tens_esprit(x, I, L.tens, groups = list(1:2), status = FALSE)
  pars.tssa$rate1[i] <- max(par.tssa[[1]]$rates[1], par.tssa[[1]]$rates[2])
  pars.tssa$rate2[i] <- min(par.tssa[[1]]$rates[1], par.tssa[[1]]$rates[2])
  pars.tssa$freq1[i] <- min(par.tssa[[1]]$frequencies[1], par.tssa[[1]]$frequencies[2])
  pars.tssa$freq2[i] <- max(par.tssa[[1]]$frequencies[1], par.tssa[[1]]$frequencies[2])
  setTxtProgressBar(pb, i)
}
close(pb)
```
```{r, results='hold'}
cat("Rate 1, SSA: ", rrmse(rates.true[1], pars.ssa$rate1), '\n')
cat("Rate 1, HO-SSA: ", rrmse(rates.true[1], pars.tssa$rate1), '\n')
cat("Rate 2, SSA: ", rrmse(rates.true[2], pars.ssa$rate2), '\n')
cat("Rate 2, HO-SSA: ", rrmse(rates.true[2], pars.tssa$rate2), '\n')
cat("Freq 1, SSA: ", rrmse(freqs.true[1], pars.ssa$freq1), '\n')
cat("Freq 1, HO-SSA: ", rrmse(freqs.true[1], pars.tssa$freq1), '\n')
cat("Freq 2, SSA: ", rrmse(freqs.true[2], pars.ssa$freq2), '\n')
cat("Freq 2, HO-SSA: ", rrmse(freqs.true[2], pars.tssa$freq2), '\n')
```


```{r}
len.out <- 16
sds <- seq(from = 0, to = 0.2, length.out = len.out)

set.seed(10)

n <- 25
L <- 15
I <- 14; L.tens <- 8

# no rates
rates.true <- c(0, 0)
# both rates -0.01
# rates.true <- c(-0.01, -0.01)
# both rates -0.02
# rates.true <- c(-0.02, -0.02)
# rates from paper
# rates.true <- c(-0.01, -0.02)

freqs.true <- c(0.2, 0.22)
signal <- exp((rates.true[1] + 2i * pi * freqs.true[1]) * 0:(n - 1)) +
  exp((rates.true[2] + 2i * pi * freqs.true[2]) * 0:(n - 1))

R <- 100
l.range <- 2:4

lambda.mean <- list(ssa = matrix(numeric(length(l.range) * len.out), nrow = length(l.range)), 
                    tssa = matrix(numeric(length(l.range) * len.out), nrow = length(l.range)))
colnames(lambda.mean$ssa) <- round(sds, 2)
colnames(lambda.mean$tssa) <- round(sds, 2)
rownames(lambda.mean$ssa) <- l.range
rownames(lambda.mean$tssa) <- l.range

pb <- txtProgressBar(max = R * len.out, style = 3)

for (j in seq_along(sds)) {
  sd <- sds[j]
  
  lambda.ssa <- matrix(numeric(length(l.range) * R), nrow = length(l.range))
  lambda.tssa <- matrix(numeric(length(l.range) * R), nrow = length(l.range))
  
  for (i in seq(R)) {
    noise <- CCSWGN(n, mean = 0, sd = sd)
    x <- signal + noise
    
    lambda.ssa[,i] <- svd(Rssa::hankel(x, L))$d[l.range]
    
    Z <- hosvd_mod(tens3(x, I, L.tens), status = FALSE)$Z[,, l.range, drop = FALSE]@data
    lambda.tssa[,i] <- apply(Z, 3, fnorm_complex)
    
    setTxtProgressBar(pb, (j - 1) * R + i)
  }
  
  lambda.mean$ssa[,j] <- rowMeans(lambda.ssa)
  lambda.mean$tssa[,j] <- rowMeans(lambda.tssa)
}
close(pb)
```


```{r}
scree.plots.ssa <- list()
scree.plots.tssa <- list()

for (j in 1:len.out) {
  df <- data.frame(l_ssa = lambda.mean$ssa[, j], l_tssa = lambda.mean$tssa[, j])
  
  scree.plots.ssa[[j]] <- df |> ggplot(aes(x = l.range, y = l_ssa)) +
    geom_point(size = 4) + geom_line() +
    labs(title = paste0("SSA, sd = ", round(sds[j], 2)),
         x = "Index", y = "Lambda") +
    ylim(c(min(lambda.mean$ssa), max(lambda.mean$ssa)))
  
  scree.plots.tssa[[j]] <- df |> ggplot(aes(x = l.range, y = l_tssa)) +
    geom_point(size = 4) + geom_line() +
    labs(title = paste0("HO-SSA, sd = ", round(sds[j], 2)),
         x = "Index", y = "Lambda") +
    ylim(c(min(lambda.mean$tssa), max(lambda.mean$tssa)))
}

ggsave("./img/Scree_plots_ssa.pdf",
       marrangeGrob(grobs = scree.plots.ssa, ncol = 2, nrow = 3,
                    layout_matrix = matrix(seq_len(2 * 3), nrow = 3, byrow = TRUE)),
       width = 7, height = 7)

ggsave("./img/Scree_plots_tssa.pdf",
       marrangeGrob(grobs = scree.plots.tssa, ncol = 2, nrow = 3,
                    layout_matrix = matrix(seq_len(2 * 3), nrow = 3, byrow = TRUE)),
       width = 7, height = 7)
```


```{r 1d-comparison-for-sds, results='hide'}
len.out <- 16
sds <- seq(from = 0.01, to = 0.2, length.out = len.out)
# sds <- seq(from = 0.01, to = 0.06, length.out = len.out)
set.seed(10)

n <- 25
L <- 15
I <- 14; L.tens <- 8
# no rates
# rates.true <- c(0, 0)
# both rates -0.01
# rates.true <- c(-0.01, -0.01)
# both rates -0.02
# rates.true <- c(-0.02, -0.02)
# rates from paper
rates.true <- c(-0.01, -0.02)

freqs.true <- c(0.2, 0.22)
signal <- exp((rates.true[1] + 2i * pi * freqs.true[1]) * 0:(n - 1)) +
  exp((rates.true[2] + 2i * pi * freqs.true[2]) * 0:(n - 1))

groups <- list(1:2)

R <- 500

rate1.rrmse <- list(ssa = numeric(len.out), tssa = numeric(len.out))
rate2.rrmse <- list(ssa = numeric(len.out), tssa = numeric(len.out))
freq1.rrmse <- list(ssa = numeric(len.out), tssa = numeric(len.out))
freq2.rrmse <- list(ssa = numeric(len.out), tssa = numeric(len.out))

pb <- txtProgressBar(max = R * len.out, style = 3)

for (j in seq_along(sds)) {
  pars.ssa <- list(
    rate1 = numeric(R),
    rate2 = numeric(R),
    freq1 = numeric(R),
    freq2 = numeric(R)
  )
  
  pars.tssa <- list(
    rate1 = numeric(R),
    rate2 = numeric(R),
    freq1 = numeric(R),
    freq2 = numeric(R)
  )
  
  sd <- sds[j]
  
  for (i in seq(R)) {
    noise <- CCSWGN(n, mean = 0, sd = sd)
    x <- signal + noise
    x.ssa <- ssa(x, L = L)
    
    par.ssa <- parestimate(x.ssa, groups = groups)
    pars.ssa$rate1[i] <- max(par.ssa$rates[1], par.ssa$rates[2])
    pars.ssa$rate2[i] <- min(par.ssa$rates[1], par.ssa$rates[2])
    pars.ssa$freq1[i] <- min(par.ssa$frequencies[1], par.ssa$frequencies[2])
    pars.ssa$freq2[i] <- max(par.ssa$frequencies[1], par.ssa$frequencies[2])
    
    par.tssa <- tens_esprit(x, I, L.tens, groups = groups, status = FALSE)
    pars.tssa$rate1[i] <- max(par.tssa[[1]]$rates[1], par.tssa[[1]]$rates[2])
    pars.tssa$rate2[i] <- min(par.tssa[[1]]$rates[1], par.tssa[[1]]$rates[2])
    pars.tssa$freq1[i] <- min(par.tssa[[1]]$frequencies[1], par.tssa[[1]]$frequencies[2])
    pars.tssa$freq2[i] <- max(par.tssa[[1]]$frequencies[1], par.tssa[[1]]$frequencies[2])
    
    setTxtProgressBar(pb, (j - 1) * R + i)
  }
  
  rate1.rrmse$ssa[j] <- rrmse(rates.true[1], pars.ssa$rate1)
  rate1.rrmse$tssa[j] <- rrmse(rates.true[1], pars.tssa$rate1)
  rate2.rrmse$ssa[j] <- rrmse(rates.true[2], pars.ssa$rate2)
  rate2.rrmse$tssa[j] <- rrmse(rates.true[2], pars.tssa$rate2)
  freq1.rrmse$ssa[j] <- rrmse(freqs.true[1], pars.ssa$freq1)
  freq1.rrmse$tssa[j] <- rrmse(freqs.true[1], pars.tssa$freq1)
  freq2.rrmse$ssa[j] <- rrmse(freqs.true[2], pars.ssa$freq2)
  freq2.rrmse$tssa[j] <- rrmse(freqs.true[2], pars.tssa$freq2)
}
close(pb)
```

```{r}
signal.plot.df <- data.frame(
  re_1 = Re(exp((rates.true[1] + 2i * pi * freqs.true[1]) * 0:(n - 1))), 
  im_1 = Im(exp((rates.true[1] + 2i * pi * freqs.true[1]) * 0:(n - 1))),
  re_2 = Re(exp((rates.true[2] + 2i * pi * freqs.true[2]) * 0:(n - 1))),
  im_2 = Im(exp((rates.true[2] + 2i * pi * freqs.true[2]) * 0:(n - 1))),
  index = 1:n) |> mutate(re_sum = re_1 + re_2, im_sum = im_1 + im_2)


signal.plot.df |> pivot_longer(c(re_1, re_2, re_sum), names_to = "Re_num", 
                               names_prefix = "re_", values_to = "Re") |>
  ggplot(aes(x = index)) + geom_line(aes(y = Re, col = Re_num, linetype = Re_num), lwd = 1.2)

signal.plot.df |> pivot_longer(c(im_1, im_2, im_sum), names_to = "Im_num", 
                               names_prefix = "im_", values_to = "Im") |>
  ggplot(aes(x = index)) + geom_line(aes(y = Im, col = Im_num, linetype = Im_num), lwd = 1.2)
```


```{r}
rate1.df <- rate1.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
rate1.plot <- rate1.df |> ggplot() +
  geom_line(aes(
    x = sd,
    y = RRMSE,
    colour = type,
    linetype = type
  ), lwd = 1.2)

plot.save(rate1.plot,
          "./img/rate1.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```

```{r}
rate2.df <- rate2.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
rate2.plot <- rate2.df |> ggplot() + geom_line(aes(
  x = sd,
  y = RRMSE,
  colour = type,
  linetype = type
), lwd = 1.2)

plot.save(rate2.plot,
          "./img/rate2.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```

```{r}
freq1.df <- freq1.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
freq1.plot <- freq1.df |> ggplot() + geom_line(aes(
  x = sd,
  y = RRMSE,
  colour = type,
  linetype = type
), lwd = 1.2)

plot.save(freq1.plot,
          "./img/freq1.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```
```{r}
freq2.df <- freq2.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
freq2.plot <- freq2.df |> ggplot() + geom_line(aes(
  x = sd,
  y = RRMSE,
  colour = type,
  linetype = type
), lwd = 1.2)

plot.save(freq2.plot,
          "./img/freq2.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```

```{r complex-nd-esprit}
cmesprit <- function(s, L, groups, qrtol = 1e-07) {
  H <- apply(s, 2, Rssa::hankel, L = L, simplify = FALSE) |>
    Reduce(cbind, x = _) 
  
  max_rank <- max(sapply(groups, max))
  H.svd <- svd(H, nu = max_rank, nv = 0)
  estimates <- list()
  for (i in seq(groups)) {
    U <- H.svd$u[, groups[[i]], drop = FALSE]
    Z <- qr.solve(U[-nrow(U), ], U[-1, ], qrtol)
    poles <- eigen(Z, only.values = TRUE)$values
    estimates[[i]] <- list(
      poles = poles,
      rates = Re(log(poles)),
      frequencies = Im(log(poles)) / 2 / pi
    )
  }
  estimates
}
```


```{r test-nd-ssa-esprit-no-noise}
set.seed(10)

n <- 25
Q <- 12
coef <- matrix(CCSWGN(2 * Q), ncol = 2)

x <- exp((-0.01 + 2i * pi * 0.2) * 0:(n - 1)) %o% coef[, 1] + 
  exp((-0.02 + 2i * pi * 0.22) * 0:(n - 1)) %o% coef[, 2]
L <- 13
pars <- cmesprit(x, L = L, groups = list(1:2))[[1]]
cat("Rates:\n", pars$rates, "\nFrequencies:\n", pars$frequencies)
```

```{r test-nd-tens-esprit-no-noise}
set.seed(10)

n <- 25
Q <- 12
coef <- matrix(CCSWGN(2 * Q), ncol = 2)

x <- exp((-0.01 + 2i * pi * 0.2) * 0:(n - 1)) %o% coef[, 1] + 
  exp((-0.02 + 2i * pi * 0.22) * 0:(n - 1)) %o% coef[, 2]
L <- 13
pars <- tens_esprit(x, I, L, groups = list(1:2), kind = "HO-MSSA", est_dim = 1, status = FALSE)
cat("Rates:\n", pars[[1]]$rates, "\nFrequencies:\n", pars[[1]]$frequencies)
```


```{r nd-comparison-for-sds}
len.out <- 16
sds <- seq(from = 0.1, to = 0.4, length.out = len.out)
set.seed(10)

n <- 25
Q <- 12
L <- 13
L.tens <- 13

# no rates
rates.true <- c(0, 0)
# both rates -0.01
# rates.true <- c(-0.01, -0.01)
# both rates -0.02
# rates.true <- c(-0.02, -0.02)
# rates from paper
# rates.true <- c(-0.01, -0.02)

freqs.true <- c(0.2, 0.22)

coef <- matrix(CCSWGN(2 * Q), ncol = 2)

signal.mult <- exp((rates.true[1] + 2i * pi * freqs.true[1]) * 0:(n - 1)) %o% coef[, 1] + 
  exp((rates.true[2] + 2i * pi * freqs.true[2]) * 0:(n - 1)) %o% coef[, 2]

R <- 1000

rate1.mult.rrmse <- list(mssa = numeric(len.out), tmssa = numeric(len.out))
rate2.mult.rrmse <- list(mssa = numeric(len.out), tmssa = numeric(len.out))
freq1.mult.rrmse <- list(mssa = numeric(len.out), tmssa = numeric(len.out))
freq2.mult.rrmse <- list(mssa = numeric(len.out), tmssa = numeric(len.out))

pb <- txtProgressBar(max = R * len.out, style = 3)

for (j in seq_along(sds)) {
  pars.mssa <- list(
    rate1 = numeric(R),
    rate2 = numeric(R),
    freq1 = numeric(R),
    freq2 = numeric(R)
  )
  
  pars.tmssa <- list(
    rate1 = numeric(R),
    rate2 = numeric(R),
    freq1 = numeric(R),
    freq2 = numeric(R)
  )
  
  sd <- sds[j]
  
  for (i in seq(R)) {
    noise <- CCSWGN(n, mean = 0, sd = sd)
    x <- signal.mult + noise
    
    par.mssa <- cmesprit(x, L = L, groups = list(1:2))
    pars.mssa$rate1[i] <- max(par.mssa[[1]]$rates[1], par.mssa[[1]]$rates[2])
    pars.mssa$rate2[i] <- min(par.mssa[[1]]$rates[1], par.mssa[[1]]$rates[2])
    pars.mssa$freq1[i] <- min(par.mssa[[1]]$frequencies[1], par.mssa[[1]]$frequencies[2])
    pars.mssa$freq2[i] <- max(par.mssa[[1]]$frequencies[1], par.mssa[[1]]$frequencies[2])
    
    par.tmssa <- tens_esprit(x, L.tens, kind = "HO-MSSA", est_dim = 1, groups = list(1:2), status = FALSE)
    pars.tmssa$rate1[i] <- max(par.tmssa[[1]]$rates[1], par.tmssa[[1]]$rates[2])
    pars.tmssa$rate2[i] <- min(par.tmssa[[1]]$rates[1], par.tmssa[[1]]$rates[2])
    pars.tmssa$freq1[i] <- min(par.tmssa[[1]]$frequencies[1], par.tmssa[[1]]$frequencies[2])
    pars.tmssa$freq2[i] <- max(par.tmssa[[1]]$frequencies[1], par.tmssa[[1]]$frequencies[2])
    
    setTxtProgressBar(pb, (j - 1) * R + i)
  }
  
  rate1.mult.rrmse$mssa[j] <- rrmse(rates.true[1], pars.mssa$rate1)
  rate1.mult.rrmse$tmssa[j] <- rrmse(rates.true[1], pars.tmssa$rate1)
  rate2.mult.rrmse$mssa[j] <- rrmse(rates.true[2], pars.mssa$rate2)
  rate2.mult.rrmse$tmssa[j] <- rrmse(rates.true[2], pars.tmssa$rate2)
  freq1.mult.rrmse$mssa[j] <- rrmse(freqs.true[1], pars.mssa$freq1)
  freq1.mult.rrmse$tmssa[j] <- rrmse(freqs.true[1], pars.tmssa$freq1)
  freq2.mult.rrmse$mssa[j] <- rrmse(freqs.true[2], pars.mssa$freq2)
  freq2.mult.rrmse$tmssa[j] <- rrmse(freqs.true[2], pars.tmssa$freq2)
}
close(pb)
```

```{r}
save = TRUE

rate1.df <- rate1.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
rate1.plot <- rate1.df |> ggplot() +
  geom_line(aes(
    x = sd,
    y = RRMSE,
    colour = type,
    linetype = type
  ), lwd = 1.2)

plot.save(rate1.plot,
          "./img/rate1_nd.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```

```{r}
rate2.df <- rate2.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
rate2.plot <- rate2.df |> ggplot() + geom_line(aes(
  x = sd,
  y = RRMSE,
  colour = type,
  linetype = type
), lwd = 1.2)

plot.save(rate2.plot,
          "./img/rate2_nd.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```

```{r}
freq1.df <- freq1.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
freq1.plot <- freq1.df |> ggplot() + geom_line(aes(
  x = sd,
  y = RRMSE,
  colour = type,
  linetype = type
), lwd = 1.2)

plot.save(freq1.plot,
          "./img/freq1_nd.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```

```{r}
freq2.df <- freq2.rrmse |> as.data.frame() |> mutate(sd = sds) |>
  pivot_longer(!sd, names_to = "type", values_to = "RRMSE")
freq2.plot <- freq2.df |> ggplot() + geom_line(aes(
  x = sd,
  y = RRMSE,
  colour = type,
  linetype = type
), lwd = 1.2)

plot.save(freq2.plot,
          "./img/freq2_nd.pdf",
          pdf,
          width = 9,
          height = 6, save = save)
```
