---
title: "HTLSDstack"
output: html_document
---

```{r setup, include=FALSE}
library(gridExtra)
library(latex2exp)
library(Rssa)
library(rTensor)
library(ggplot2)
library(dplyr)
library(tidyr)
library(future.apply)
library(progressr)

setwd(rprojroot::find_rstudio_root_file())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
source(file = "./Research/TSSA.R")
```

```{r enable progressr, eval = FALSE}
# This commands should be executed in R console, not as a chunk
# Otherwise they fail
progressr::handlers(global = TRUE)
progressr::handlers("progress")
```

# Functions
## Errors and snr
```{r}
rmse <- function(true, pred) {
  sqrt(mean((pred - true)^2))
}

rmse_mat <- function(true, pred) {
  apply(cbind(true, pred), 1, function(v) rmse(v[1], v[-1]))
}

rmse_ts <- function(true, pred) {
  sqrt(mean(apply(pred, 2, function(p) mean((true - p)^2))))
}

rrmse_freq <- function(true, pred) {
  rmse_mat(true, pred) * 100 / (0.5 * abs(true[1] - true[2]))
}

sd_to_snr <- function(s, sd) {
  10 * log10(sum(abs(s)^2) / sd^2)
}

snr_to_sd <- function(s, snr) {
  sqrt(sum(abs(s)^2) / 10^(snr / 10))
}
```

## Compares
```{r}
compare_htls_c <- function() {
  noise <- CCSWGN(N, 0, sd)
  x <- s + noise
  
  est <- list(
    esprit = parestimate(ssa(x, L = L_esprit), groups = groups_esprit, drop = FALSE),
    htlsd = HTLSDstack(
      x,
      D = D,
      L = L_htlsd,
      groups = groups_htlsd,
      method = "base"
    ),
    tens1 = HTLSDstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_1,
      est_dim = est_dim,
      status = FALSE
    ),
    tens2 = HTLSDstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_2,
      est_dim = est_dim,
      status = FALSE
    )
  )
  
  sapply(est, function(m)
    sapply(m, function(e)
      c(
        rates = e$rates, frequencies = e$freq
      )))
}

compare_htls_r <- function() {
  noise <- rnorm(N, 0, sd)
  x <- s + noise
  
  est <- list(
    esprit = parestimate(ssa(x, L = L_esprit), groups = groups_esprit, drop = FALSE),
    htlsd = HTLSDstack(
      x,
      D = D,
      L = L_htlsd,
      groups = groups_htlsd,
      method = "base"
    ),
    tens1 = HTLSDstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_1,
      est_dim = est_dim,
      status = FALSE
    ),
    tens2 = HTLSDstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_2,
      est_dim = est_dim,
      status = FALSE
    )
  )
  sapply(est, function(m)
  sapply(m, function(e)
    c(
      rates = e$rates, frequencies = e$freq
    )))
}
  
  compare_htls_r2 <- function() {
    noise <- rnorm(N, 0, sd)
    x <- s + noise
    
    est <- list(
      esprit = parestimate(ssa(x, L = L_esprit), groups = groups_esprit, drop = FALSE),
      htlsd = HTLSDstack(
        x,
        D = D,
        L = L_htlsd,
        groups = groups_htlsd,
        method = "base"
      ),
      hoesprit = tens_esprit(
        x,
        L = L_hoesprit,
        groups = groups_hoesprit,
        kind = "HO-SSA",
        decomp = "HOSVD",
        est_dim = 3,
        status = FALSE
      ),
      tens1 = HTLSDstack(
        x,
        D = D,
        L = L_tens,
        groups = groups_tens,
        method = "hooi",
        r3 = r3_1,
        est_dim = est_dim,
        status = FALSE
      ),
      tens2 = HTLSDstack(
        x,
        D = D,
        L = L_tens,
        groups = groups_tens,
        method = "hooi",
        r3 = r3_2,
        est_dim = est_dim,
        status = FALSE
      )
    )
    
  sapply(est, function(m)
    sapply(m, function(e)
      c(
        rates = e$rates, frequencies = e$freq
      )))
}

compare_rec_r <- function() {
  noise <- rnorm(N, 0, sd)
  x <- s + noise
  
  rec <- list(
    ssa = reconstruct(ssa(x, L = L_ssa), groups = groups_ssa),
    ssad = SSADstack(
      x,
      D = D,
      L = L_ssad,
      groups = groups_ssad,
      method = "base"
    ),
    tens1 = SSADstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_1,
      status = FALSE
    ),
    tens2 = SSADstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_2,
      status = FALSE
    )
  )
  
  sapply(rec, function(m)
    Reduce("+", m))
}

compare_rec_r2 <- function() {
  noise <- rnorm(N, 0, sd)
  x <- s + noise
  
  rec <- list(
    ssa = reconstruct(ssa(x, L = L_ssa), groups = groups_ssa),
    ssad = SSADstack(
      x,
      D = D,
      L = L_ssad,
      groups = groups_ssad,
      method = "base"
    ),
    hossa = tens_ssa_reconstruct(
      x,
      L_hossa,
      groups = groups_hossa,
      decomp = "hosvd",
      trunc_dims = td_hossa,
      status = FALSE
    ),
    tens1 = SSADstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_1,
      status = FALSE
    ),
    tens2 = SSADstack(
      x,
      D = D,
      L = L_tens,
      groups = groups_tens,
      method = "hooi",
      r3 = r3_2,
      status = FALSE
    )
  )
  
  sapply(rec, function(m)
    Reduce("+", m))
}
```


# Examples from [paper](https://doi.org/10.1002/cem.1212)
```{r}

# Example 1
plot_name <- "complex_param_rmse"
A <- c(1, 1)
phi <- c(0, 0)
rate <- c(0, 0)
freq <- c(0.2, 0.205)
L_esprit <- 500
L_htlsd <- 50
L_tens <- 50
D <- 10
groups_esprit <- list(1:2)
groups_htlsd <- list(1:2)
groups_tens <- list(1:2)
r3_1 <- 2
r3_2 <- 1
est_dim <- 1
dt <- 0.1
N <- 990

s <- colSums(A * exp(1i * phi) * exp((-rate + 1i * 2 * pi * freq) %o% seq(
  from = 0,
  length.out = N,
  by = dt
)))
```

```{r warning=FALSE}
# sd <- snr_to_sd(s, snr = 35)
out_len <- 16
sds <- seq(0, 1.5, length.out = out_len)
rmse_df1 <- data.frame(sd = sds, esprit = numeric(out_len), HTLSDstack = numeric(out_len),
                      tens1 = numeric(out_len), tens2 = numeric(out_len))
rmse_df2 <- data.frame(sd = sds, esprit = numeric(out_len), HTLSDstack = numeric(out_len),
                      tens1 = numeric(out_len), tens2 = numeric(out_len))
R <- 100
for (i in seq(sds)) {
  print(i)
  sd <- sds[i]
  with(plan(multisession), {
    batch_estims <- function(R) {
      p <- progressor(R)
      future_replicate(R, {
        p()
        compare_htls_c()
      }, simplify = "array", future.seed = 5)
    }
    estims <- batch_estims(R)
  })
  
  freq_estims <- apply(estims[3:4, , ], 2:3, function(v)
    c(v[which.min(abs(v))], v[which.max(abs(v))]) / dt)
  freq_rmse <- apply(freq_estims, 2, rmse_mat, true = freq)
  rmse_df1[i,-1] <- freq_rmse[1,]
  rmse_df2[i,-1] <- freq_rmse[2,]
}

save(rmse_df1, rmse_df2, file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
```

```{r}
load(file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
sd_bound <- 0.75
p1 <- rmse_df1 |> filter(sd <= sd_bound) |> pivot_longer(cols = -sd,
                                                   names_to = "Method",
                                                   values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  ggtitle(TeX(sprintf("$\\nu = %5.3f$", freq[1])))
p2 <- rmse_df1 |> filter(sd >= sd_bound) |> pivot_longer(cols = -sd,
                                                    names_to = "Method",
                                                    values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  ggtitle(TeX(sprintf("$\\nu = %5.3f$", freq[1])))
pdf(paste0("./img/htlsd_", plot_name, "_1.pdf"), width = 9, height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)

p1 <- rmse_df2 |> filter(sd <= sd_bound) |> pivot_longer(cols = -sd, names_to = "Method", values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) + 
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  ggtitle(TeX(sprintf("$\\nu = %5.3f$", freq[2])))
p2 <- rmse_df2 |> filter(sd >= sd_bound) |> pivot_longer(cols = -sd, names_to = "Method", values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) + 
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 2", "Tesnor, r3 = 1")) +
  ggtitle(TeX(sprintf("$\\nu = %5.3f$", freq[2])))
pdf(paste0("./img/htlsd_", plot_name, "_2.pdf"), width = 9, height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)
```

# Real case with same parameters by L
```{r}
plot_name <- "real_param_rmse"
N <- 990
A <- c(1, 1)
phi <- c(0, 0)
rate <- c(0, 0)
freq <- c(0.2, 0.205)
D <- 10
Ls_esprit <- as.integer(seq(from = N %/% 3, to = 2 * N %/% 3, length.out = 20))
Ls_dstack <- as.integer(seq(from = (N %/% D) %/% 3, to = 2 * (N %/% D) %/% 3, length.out = 20))
groups_esprit <- list(1:4)
groups_htlsd <- list(1:4)
groups_tens <- list(1:4)
r3_1 <- 4
r3_2 <- 1
est_dim <- 1
dt <- 0.1


s <- colSums(A * exp(-rate) * cos(phi + 2 * pi * freq %o% seq(
  from = 0,
  length.out = N,
  by = dt
)))
```

```{r warning=FALSE}
# sd <- snr_to_sd(s, snr = 35)
# out_len <- 16
# sds <- seq(0, 1.5, length.out = out_len)
sds <- c(0, 0.2, 0.6)
sd_len <- length(sds)
Ls_len <- length(Ls_esprit)
out_len <- sd_len * Ls_len
rmse_df <- data.frame(
  sd = rep(sds, each = Ls_len),
  Ls_esprit = rep(Ls_esprit, sd_len),
  Ls_htlsd = rep(Ls_dstack, sd_len),
  Ls_tens = rep(Ls_dstack, sd_len),
  esprit = numeric(out_len),
  HTLSDstack = numeric(out_len),
  tens1 = numeric(out_len),
  tens2 = numeric(out_len)
)
Ls_df <- data.frame()

R <- 100
for (i in seq(sds)) {
  sd <- sds[i]
  for (j in seq(Ls_esprit)) {
    L_esprit <- Ls_esprit[j]
    L_htlsd <- Ls_dstack[j]
    L_tens <- Ls_dstack[j]
    print(sprintf(
      "sd = %3.1f, (L_base, L_dstack) = (%d, %d)",
      sd,
      L_esprit,
      L_htlsd
    ))
    with(plan(multisession), {
      batch_estims <- function(R) {
        p <- progressor(R)
        future_replicate(R, {
          p()
          compare_htls_r()
        }, simplify = "array", future.seed = 5)
      }
      if (sd == 0)
        estims <- batch_estims(1)[, , ] %o% rep(1, R)
      else
        estims <- batch_estims(R)
    })
    
    freq_estims <- apply(estims[5:8, , ], 2:3, function(v)
      sort(kmeans(abs(v), 2)$centers))
    
    freq_rmse <- apply(freq_estims, 2, rmse_mat, true = freq * dt)
    rmse_df[(i - 1) * Ls_len + j, -(1:4)] <- sqrt((freq_rmse[1, ]^2 + freq_rmse[2, ]^2) / 2)
  }
}

# save(rmse_df, file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
save(rmse_df, file = paste0("./Research/comp_results/htlsd_byL_", plot_name, ".RData"))
```

```{r}
plot_name <- "real_param_rmse"
load(file = paste0("./Research/comp_results/htlsd_byL_", plot_name, ".RData"))
methods_names <- list(esprit = "ESPRIT", HTLSDstack = "HTLSDstack", 
                      tens1 = "Tensor, r3 = 4", tens2 = "Tensor, r3 = 1")
extreme_rmse <- rmse_df |>  pivot_longer(cols = esprit:tens2,
                                         names_to = "Method",
                                         values_to = "RMSE") |>
  group_by(sd, Method) |> summarize(min = min(RMSE), max = max(RMSE))

for (sd_k in sds[sds != 0]) {
  ext_rmse_sd <- filter(extreme_rmse, sd == sd_k)
  ext_rmse_oth <- filter(ext_rmse_sd, Method != "esprit")
  ext_rmse_esprit <- filter(ext_rmse_sd, Method == "esprit")
  p1 <- rmse_df |> filter(sd == sd_k) |>
    pivot_longer(cols = esprit:tens2,
                 names_to = "Method",
                 values_to = "RMSE") |>
    filter(Method == "esprit") |>
    ggplot(aes(x = Ls_esprit, y = RMSE)) +
    geom_line() +
    geom_hline(
      yintercept = min(ext_rmse_oth$min),
      linetype = 2,
      color = "gray20"
    ) +
    scale_y_continuous(limits = c(min(ext_rmse_sd$min), max(ext_rmse_sd$max))) +
    annotate(
      "label",
      x = (Ls_esprit[Ls_len] + Ls_esprit[1]) * 0.40,
      y = min(ext_rmse_oth$min) * (1.035 + (sd_k == 0.6) * 4.6),
      label = paste0("Minimum for other methods\n(achieved on ", methods_names[[ext_rmse_oth$Method[which.min(ext_rmse_oth$min)]]], ")"),
      size = 6
    ) +
    ggtitle(paste0("ESPRIT, sd = ", sd_k)) +
    theme_minimal() +
    theme(text = element_text(size = 20)) +
    xlab("L")
  
  p2 <- rmse_df |> filter(sd == sd_k) |>
    pivot_longer(cols = esprit:tens2,
                 names_to = "Method",
                 values_to = "RMSE") |>
    filter(Method != "esprit") |>
    ggplot(aes(x = Ls_htlsd, y = RMSE)) +
    geom_line(aes(col = Method, lty = Method)) +
    geom_hline(
      yintercept = min(ext_rmse_esprit$min),
      linetype = 2,
      color = "gray20"
    ) +
    scale_y_continuous(limits = c(min(ext_rmse_sd$min), max(ext_rmse_sd$max))) +
    annotate(
      "label",
      x = (Ls_dstack[Ls_len] + Ls_dstack[1]) * 0.41,
      y = min(ext_rmse_esprit$min) * 1.02,
      label = paste0("Minimum for ESPRIT"),
      size = 6
    ) +
    scale_linetype_discrete(labels = c("Dstack ESPRIT", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
    scale_color_discrete(labels = c("Dstack ESPRIT", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
    ggtitle(paste0("Dstack methods, sd = ", sd_k)) +
    theme_minimal() +
    theme(text = element_text(size = 20)) +
    xlab("L")
  pdf(paste0("./img/htlsd_byL_", plot_name, "_esprit_", which(sds == sd_k), ".pdf"),
      width = 9,
      height = 7)
    print(p1)
  dev.off()
  pdf(paste0("./img/htlsd_byL_", plot_name, "_dstack_", which(sds == sd_k), ".pdf"),
      width = 9,
      height = 7)
    print(p2)
  dev.off()
  print(p1)
  print(p2)
}
```

```{r}
plot_name <- "real_param_rmse"
load(file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
sd_bound <- 0.3

p1 <- rmse_df |> filter(sd <= sd_bound) |> pivot_longer(cols = -sd,
                                                   names_to = "Method",
                                                   values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) 
p2 <- rmse_df |> filter(sd >= sd_bound) |> pivot_longer(cols = -sd,
                                                    names_to = "Method",
                                                    values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("ESPRIT", "HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) 
pdf(paste0("./img/htlsd_", plot_name, ".pdf"), width = 9, height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)


p1 <- rmse_df |> filter(sd <= sd_bound) |> select(-esprit) |> pivot_longer(cols = -sd,
                                                    names_to = "Method",
                                                    values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1"))
p2 <- rmse_df |> filter(sd >= sd_bound) |> select(-esprit) |> pivot_longer(cols = -sd,
                                                    names_to = "Method",
                                                    values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("HTLSDstack", "Tensor, r3 = 4", "Tesnor, r3 = 1"))
pdf(paste0("./img/htlsd_", plot_name, "_noesprit.pdf"), width = 9, height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)
```

# Real case with same parameters (short)
```{r}
plot_name <- "short_real_param_rmse"
A <- c(1, 1)
phi <- c(0, 0)
rate <- c(0, 0)
freq <- c(0.2, 0.205)
L_esprit <- 50
L_hoesprit <- c(49, 48)
L_htlsd <- 10
L_tens <- 10
D <- 5
groups_esprit <- list(1:4)
groups_hoesprit <- list(1:4)
groups_htlsd <- list(1:4)
groups_tens <- list(1:4)
r3_1 <- 4
r3_2 <- 1
est_dim <- 1
dt <- 0.1
N <- 100

s <- colSums(A * exp(-rate) * cos(phi + 2 * pi * freq %o% seq(
  from = 0,
  length.out = N,
  by = dt
)))
```

```{r warning=FALSE}
# sd <- snr_to_sd(s, snr = 35)
out_len <- 16
sds <- seq(0, 1.5, length.out = out_len)
rmse_df <- data.frame(sd = sds, esprit = numeric(out_len), hoesprit =  numeric(out_len),
                      HTLSDstack = numeric(out_len),
                      tens1 = numeric(out_len), tens2 = numeric(out_len))

R <- 100
for (i in seq(sds)) {
  print(i)
  sd <- sds[i]
  with(plan(multisession), {
    batch_estims <- function(R) {
      p <- progressor(R)
      future_replicate(R, {
        p()
        compare_htls_r2()
      }, simplify = "array", future.seed = 5)
    }
    if (sd == 0)
      estims <- batch_estims(1)[,,] %o% rep(1, R)
    else
      estims <- batch_estims(R)
  })

  freq_estims <- apply(estims[5:8, , ], 2:3, function(v)
    sort(kmeans(abs(v), 2)$centers))

  freq_rmse <- apply(freq_estims, 2, rmse_mat, true = freq * dt)
  rmse_df[i,-1] <- sqrt((freq_rmse[1,]^2 + freq_rmse[2,]^2) / 2)
}
save(rmse_df, file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
```

```{r}
plot_name <- "short_real_param_rmse"
load(file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
sd_bound <- 0.3

p1 <- rmse_df |> filter(sd <= sd_bound) |> pivot_longer(cols = -sd,
                                                        names_to = "Method",
                                                        values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c(
    "ESPRIT",
    "HO-ESPRIT",
    "HTLSDstack",
    "Tensor, r3 = 4",
    "Tesnor, r3 = 1"
  )) +
  scale_color_discrete(labels = c(
    "ESPRIT",
    "HO-ESPRIT",
    "HTLSDstack",
    "Tensor, r3 = 4",
    "Tesnor, r3 = 1"
  ))
p2 <- rmse_df |> filter(sd >= sd_bound) |> pivot_longer(cols = -sd,
                                                        names_to = "Method",
                                                        values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c(
    "ESPRIT",
    "HO-ESPRIT",
    "HTLSDstack",
    "Tensor, r3 = 4",
    "Tesnor, r3 = 1"
  )) +
  scale_color_discrete(labels = c(
    "ESPRIT",
    "HO-ESPRIT",
    "HTLSDstack",
    "Tensor, r3 = 4",
    "Tesnor, r3 = 1"
  ))
pdf(paste0("./img/htlsd_", plot_name, ".pdf"),
    width = 9,
    height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)


p1 <- rmse_df |> filter(sd <= sd_bound) |> select(-esprit, -HTLSDstack) |> pivot_longer(cols = -sd,
                                                                                        names_to = "Method",
                                                                                        values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("HO-ESPRIT", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("HO-ESPRIT", "Tensor, r3 = 4", "Tesnor, r3 = 1"))
p2 <- rmse_df |> filter(sd >= sd_bound) |> select(-esprit, -HTLSDstack) |> pivot_longer(cols = -sd,
                                                                                        names_to = "Method",
                                                                                        values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("HO-ESPRIT", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("HO-ESPRIT", "Tensor, r3 = 4", "Tesnor, r3 = 1"))
pdf(
  paste0("./img/htlsd_", plot_name, "_noesprit.pdf"),
  width = 9,
  height = 7
)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)
```

# Real case for signal reconstruction by L
```{r}
plot_name <- "real_rec_rmse"
N <- 1000
A <- c(1, 1)
phi <- c(0, 0)
rate <- c(0, 0)
freq <- c(0.2, 0.205)
D <- 10
Ls_ssa <- as.integer(seq(from = N %/% 3, to = 2 * N %/% 3, length.out = 20))
Ls_dstack <- as.integer(seq(from = (N %/% D) %/% 3, to = 2 * (N %/% D) %/% 3, length.out = 20))
groups_ssa <- list(1:4)
groups_ssad <- list(1:4)
groups_tens <- list(1:4)
r3_1 <- 4
r3_2 <- 1
dt <- 0.1

s <- colSums(A * exp(-rate) * cos(phi + 2 * pi * freq %o% seq(
  from = 0,
  length.out = N,
  by = dt
)))
```

```{r warning=FALSE}
# sd <- snr_to_sd(s, snr = 35)
sds <- c(0, 0.2, 0.6)
sd_len <- length(sds)
Ls_len <- length(Ls_ssa)
out_len <- sd_len * Ls_len
rmse_df <- data.frame(
  sd = rep(sds, each = Ls_len),
  Ls_ssa = rep(Ls_esprit, sd_len),
  Ls_dstack = rep(Ls_dstack, sd_len),
  ssa = numeric(out_len),
  SSADstack = numeric(out_len),
  tens1 = numeric(out_len),
  tens2 = numeric(out_len)
)

R <- 100
for (i in seq_along(sds)) {
  sd <- sds[i]
  for (j in seq_along(Ls_ssa)) {
    L_ssa <- Ls_ssa[j]
    L_ssad <- Ls_dstack[j]
    L_tens <- Ls_dstack[j]
    print(sprintf("sd = %3.1f, (L_base, L_dstack) = (%d, %d)", sd, L_ssa, L_ssad))
    with(plan(multisession), {
      batch_recs <- function(R) {
        p <- progressor(R)
        future_replicate(R, {
          p()
          compare_rec_r()
        }, simplify = "array", future.seed = 5)
      }
      if (sd == 0)
        recs <- batch_recs(1)[, , ] %o% rep(1, R)
      else
        recs <- batch_recs(R)
    })
    rmse_df[(i - 1) * Ls_len + j, -(1:3)] <- apply(recs, 2, rmse_ts, true = s)
  }
}
save(rmse_df, file = paste0("./Research/comp_results/htlsd_byL_", plot_name, ".RData"))
```

```{r}
plot_name <- "real_rec_rmse"
load(file = paste0("./Research/comp_results/htlsd_byL_", plot_name, ".RData"))
methods_names <- list(ssa = "SSA", SSADstack = "SSADstack", 
                      tens1 = "Tensor, r3 = 4")
extreme_rmse <- rmse_df |>  pivot_longer(cols = ssa:tens1,
                                         names_to = "Method",
                                         values_to = "RMSE") |>
  group_by(sd, Method) |> summarize(min = min(RMSE), max = max(RMSE))

for (sd_k in sds[sds != 0]) {
  ext_rmse_sd <- filter(extreme_rmse, sd == sd_k)
  ext_rmse_oth <- filter(ext_rmse_sd, Method != "ssa")
  ext_rmse_esprit <- filter(ext_rmse_sd, Method == "ssa")
  p1 <- rmse_df |> filter(sd == sd_k) |>
    pivot_longer(cols = ssa:tens1,
                 names_to = "Method",
                 values_to = "RMSE") |>
    filter(Method == "ssa") |>
    ggplot(aes(x = Ls_ssa, y = RMSE)) +
    geom_line() +
    geom_hline(
      yintercept = min(ext_rmse_oth$min),
      linetype = 2,
      color = "gray20"
    ) +
    scale_y_continuous(limits = c(min(ext_rmse_sd$min), max(ext_rmse_sd$max))) +
    annotate(
      "label",
      x = (Ls_ssa[Ls_len] + Ls_ssa[1]) * 0.4,
      y = min(ext_rmse_oth$min) * 0.94,
      label = paste0("Minimum for other methods\n(achieved on ", methods_names[[ext_rmse_oth$Method[which.min(ext_rmse_oth$min)]]], ")"),
      size = 6
    ) +
    ggtitle(paste0("SSA, sd = ", sd_k)) +
    theme_minimal() +
    theme(text = element_text(size = 20)) +
    xlab("L")
  
  p2 <- rmse_df |> filter(sd == sd_k) |>
    pivot_longer(cols = ssa:tens1,
                 names_to = "Method",
                 values_to = "RMSE") |>
    filter(Method != "ssa") |>
    ggplot(aes(x = Ls_dstack, y = RMSE)) +
    geom_line(aes(col = Method, lty = Method)) +
    geom_hline(
      yintercept = min(ext_rmse_esprit$min),
      linetype = 2,
      color = "gray20"
    ) +
    scale_y_continuous(limits = c(min(ext_rmse_sd$min), max(ext_rmse_sd$max))) +
    annotate(
      "label",
      x = (Ls_dstack[Ls_len] + Ls_dstack[1]) * 0.4,
      y = min(ext_rmse_esprit$min) * 1.08,
      label = paste0("Minimum for SSA"),
      size = 6
    ) +
    scale_linetype_discrete(labels = c("Dstack SSA", "Tensor, r3 = 4")) +
    scale_color_discrete(labels = c("Dstack SSA", "Tensor, r3 = 4")) +
    ggtitle(paste0("Dstack methods, sd = ", sd_k)) +
    theme_minimal() +
    theme(text = element_text(size = 20)) +
    xlab("L")
  pdf(paste0("./img/htlsd_byL_", plot_name, "_ssa_", which(sds == sd_k), ".pdf"),
      width = 9,
      height = 7)
    print(p1)
  dev.off()
  pdf(paste0("./img/htlsd_byL_", plot_name, "_dstack_", which(sds == sd_k), ".pdf"),
      width = 9,
      height = 7)
    print(p2)
  dev.off()
  print(p1)
  print(p2)
}
```


# Real case for signal reconstruction
```{r}
plot_name <- "real_rec_rmse"
A <- c(1, 1)
phi <- c(0, 0)
rate <- c(0, 0)
freq <- c(0.2, 0.205)
L_ssa <- 500
L_hossa <- c(499, 498)
L_ssad <- 50
L_tens <- 50
td_hossa <- 1
D <- 10
groups_ssa <- list(1:4)
groups_ssad <- list(1:4)
groups_hossa <- list(1:4)
groups_tens <- list(1:4)
r3_1 <- 4
r3_2 <- 1
dt <- 0.1
N <- 1000

s <- colSums(A * exp(-rate) * cos(phi + 2 * pi * freq %o% seq(
  from = 0,
  length.out = N,
  by = dt
)))
```

```{r warning=FALSE}
# sd <- snr_to_sd(s, snr = 35)
out_len <- 16
sds <- seq(0, 1.5, length.out = out_len)
rmse_df <- data.frame(sd = sds, esprit = numeric(out_len), HTLSDstack = numeric(out_len),
                      tens1 = numeric(out_len), tens2 = numeric(out_len))
R <- 100
for (i in seq_along(sds)) {
  print(i)
  sd <- sds[i]
  with(plan(multisession), {
    batch_recs <- function(R) {
      p <- progressor(R)
      future_replicate(R, {
        p()
        compare_rec_r()
      }, simplify = "array", future.seed = 5)
    }
    if (sd == 1)
      recs <- batch_recs(2)
    else
      recs <- batch_recs(R)
  })
  
  
  rmse_df[i,-1] <- apply(recs, 2, rmse_ts, true = s)
}
save(rmse_df, file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
```

```{r}
plot_name <- "real_rec_rmse"
load(file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
sd_bound <- 0.5
p1 <- rmse_df |> filter(sd <= sd_bound) |> pivot_longer(cols = -sd,
                                                   names_to = "Method",
                                                   values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1"))

p2 <- rmse_df |> filter(sd >= sd_bound) |> pivot_longer(cols = -sd,
                                                    names_to = "Method",
                                                    values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) 
pdf(paste0("./img/htlsd_", plot_name, ".pdf"), width = 9, height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)
```

# Real case for signal reconstruction (shorter)
```{r}
plot_name <- "short_real_rec_rmse"
A <- c(1, 1)
phi <- c(0, 0)
rate <- c(0, 0)
freq <- c(0.2, 0.205)
L_ssa <- 50
L_hossa <- c(49, 48)
L_ssad <- 10
L_tens <- 10
td_hossa <- 1
D <- 5
groups_ssa <- list(1:4)
groups_ssad <- list(1:4)
groups_hossa <- list(1:4)
groups_tens <- list(1:4)
r3_1 <- 4
r3_2 <- 1
dt <- 0.1
N <- 100

s <- colSums(A * exp(-rate) * cos(phi + 2 * pi * freq %o% seq(
  from = 0,
  length.out = N,
  by = dt
)))
```

```{r warning=FALSE}
# sd <- snr_to_sd(s, snr = 35)
out_len <- 16
sds <- seq(0, 1.5, length.out = out_len)
rmse_df <- data.frame(sd = sds, ssa = numeric(out_len), ssad = numeric(out_len),
                      hossa =  numeric(out_len),
                      tens1 = numeric(out_len), tens2 = numeric(out_len))
R <- 100
for (i in seq_along(sds)) {
  print(i)
  sd <- sds[i]
  with(plan(multisession), {
    batch_recs <- function(R) {
      p <- progressor(R)
      future_replicate(R, {
        p()
        compare_rec_r2()
      }, simplify = "array", future.seed = 5)
    }
    if (sd == 0)
      recs <- batch_recs(1)[,,] %o% rep(1, R)
    else
      recs <- batch_recs(R)
  })
  
  
  rmse_df[i,-1] <- apply(recs, 2, rmse_ts, true = s)
}
save(rmse_df, file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
```

```{r}
plot_name <- "short_real_rec_rmse"
load(file = paste0("./Research/comp_results/htlsd_", plot_name, ".RData"))
sd_bound <- 0.5
p1 <- rmse_df |> filter(sd <= sd_bound) |> pivot_longer(cols = -sd,
                                                   names_to = "Method",
                                                   values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("HO-SSA", "SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("HO-SSA", "SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1"))

p2 <- rmse_df |> filter(sd >= sd_bound) |> pivot_longer(cols = -sd,
                                                    names_to = "Method",
                                                    values_to = "RMSE") |>
  ggplot(aes(x = sd, y = RMSE)) +
  geom_line(aes(col = Method, lty = Method)) +
  scale_linetype_discrete(labels = c("HO-SSA", "SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1")) +
  scale_color_discrete(labels = c("HO-SSA", "SSA", "SSADstack", "Tensor, r3 = 4", "Tesnor, r3 = 1"))
pdf(paste0("./img/htlsd_", plot_name, ".pdf"), width = 9, height = 7)
grid.arrange(p1, p2)
dev.off()
grid.arrange(p1, p2)
```


```{r}
# Для ускорения тензорных методов посмотреть 
# View(Rssa:::decompose.ssa)
# Rssa::hbhmatmul
# RSpectra::svds
# Как происходит разложение для 2d-ssa
```

