---
title: "point_wise_errors"
output: html_document
---

```{r setup}
setwd(rprojroot::find_rstudio_root_file())
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(root.dir = rprojroot::find_rstudio_root_file())

library(Rssa)
library(svd)
library(scales)
library(rTensor)
library(ggplot2)
library(dplyr)
library(tidyr)
library(Rcpp)
library(RcppArmadillo)
library(future.apply)
library(progressr)

source(file = "./Source/TSSA.R")
source(file = "./Source/tsgen.R")
source(file = "./Source/utils.R")
```

```{r enable progressr, eval = FALSE}
# This commands should be executed in R console, not as a chunk
# Otherwise they fail
progressr::handlers(global = TRUE)
progressr::handlers("progress")
```

```{r}
pred_ssa_rec <- function() {
  noise <- rnorm(N, 0, sd)
  x <- signal + noise
  rec <- reconstruct(ssa(x, L = L_ssa), groups = groups_ssa)
  Reduce("+", rec)
}

pred_hossa_rec <- function() {
  noise <- rnorm(N, 0, sd)
  x <- signal + noise
  
  rec <- tens_ssa_reconstruct(
    x,
    unlist(L_hossa),
    groups = groups_hossa,
    # decomp = "hooi",
    svd.method = "primme",
    # svd.method = "svd",
    trunc_dims = unlist(td_hossa),
    status = FALSE
  )
  
  Reduce("+", rec)
}

pred_mssa_rec <- function() {
  noise <- rnorm(N * P, 0, sd)
  x <- signal + noise
  rec <- cmssa_reconstruct(x, L = L_mssa, groups = groups_mssa)
  Reduce("+", rec)
}

pred_homssa_rec <- function() {
  noise <- rnorm(N * P, 0, sd)
  x <- signal + noise
  
  rec <- tens_mssa_reconstruct(
    x,
    L_homssa,
    groups = groups_homssa,
    groups3 = groups3_homssa,
    decomp = tmssa_method,
    svd.method = "primme",
    status = FALSE
  )
  
  Reduce("+", rec)
}
```

```{r}
calc_errors <- function(R, pred_func, err_func, signal, progbar, seed = 5) {
  with(plan(multisession), {
    batch_recs <- function(R) {
      future_replicate(R, {
        progbar()
        pred_func()
      }, simplify = "array", future.seed = seed)
    }
    if (sd == 0)
      recs <- batch_recs(2) # don't need R because no noise present. Set to 2, because with 1 will be simplified
    else
      recs <- batch_recs(R)
  })
  
  return(err_func(signal, recs))
}

# params_grid_list: list with the parameter names as names and vectors of the parameters values as values
calc_errors_by_params <- function(params_grid_list, R, comp_func, err_func, signal, seed = 5) {
  params_grid <- expand.grid(params_grid_list)
  results <- params_grid
  results$error <- numeric(nrow(params_grid))
  q <- progressor(nrow(params_grid) * R)
  for (i in seq(nrow(params_grid))) {
    # print(paste0(names(params_grid), " = ", params_grid[i,], collapse = ", "))
    list2env(params_grid[i,], envir = parent.frame())
    results[i,]$error <- calc_errors(R, comp_func, err_func, signal, q, seed)
  }
  return(results)
}
```

```{r}
print_errors <- function(err_df) {
  err_df |> mutate(zapped_error = zapsmall(error)) |> group_by(sd) |> arrange(zapped_error, L_ssa, .by_group = TRUE)
}

print_errors_m <- function(err_df) {
  err_df |> mutate(zapped_error = zapsmall(error)) |> group_by(sd) |> arrange(zapped_error, L_mssa, .by_group = TRUE)
}

summarise_errors <- function(err_df) {
  err_df |> mutate(zapped_error = zapsmall(error)) |> group_by(sd) |> summarise(
    best = min(zapped_error),
    best_L = L[which.min(zapped_error)],
    avg = mean(zapped_error),
    worst = max(zapped_error)
  )
}
```

# Parameters for 1d series
```{r}
P_case <- ""
S.true <- 1
# S.true <- 2
S_case <- paste0("s", S.true)

# no rates
rates.true <- rep(0, S.true)
rates_case <- "_nr"
# positive small equal rates
# rates.true <- rep(0.01, S.true)
# rates_case <- "_pser"
# small equal rated
# rates.true <- c(-0.01, -0.01)
# rates_case <- "_ser"
# large equal rates
# rates.true <- c(-0.02, -0.02)
# rates_case <- "_ler"
# different rates
# rates.true <- c(-0.01, -0.02)
# rates_case <- "_dr"

# no freqs
# freqs.true <- rep(0, S.true)
# freqs_case <- "_nf"
# same freqs
# freqs.true <- rep(0.2, S.true)
# freqs_case <- "_sf"
freqs.true <- rep(1/12, S.true)
freqs_case <- "_sf"
# different freqs
# freqs.true <- c(0.2, 0.22)
# freqs_case <- "_df"
# close different freqs
# freqs.true <- c(0.02, 0.0205)
# freqs_case <- "_cdf"

# equal amplitudes
# A <- rep(1, S.true)
# A_case <- "_ea"
A <- rep(30, S.true)
A_case <- "_ea"
# different amplitudes
# A <- c(1, 2)
# A_case <- "_da"

poly.true <- 1 %o% rep(1, S.true)
poly_case <- ""
# poly.true <- c(1, 1) %o% rep(1, S.true)
# poly_case <- sprintf("p%d", dim(poly.true)[1] - 1)

# equal phases
phases.true <- rep(0, S.true)
phases_case <- "_ep"
# different phases
# phases.true <- c(0, pi / 3)
# phases_case <- "_dp"

# complex.signal <- TRUE
# complex_case <- "_c" # complex
complex.signal <- FALSE
complex_case <- "_r" # real

# N <- 25
# n_case <- ""
# N <- 100
N <- 71
n_case <- "_long"
```


## Constructing Signal
```{r}
full_case <- paste0(n_case, P_case, rates_case, freqs_case, A_case, poly_case, phases_case, complex_case)
max.r <- calc_rank(A, rates.true, freqs.true, phases.true, complex.signal, poly.true)

stopifnot(N > max.r * 2 + 1)
signal <- construct_ts(N, A, rates.true, freqs.true, phases.true, complex.signal, poly.true)
```

## Parameters grid for 1d case
```{r}
if (!is.matrix(signal)) {
groups_ssa <- list(1:max.r)

if (n_case == "") {
  Ls_ssa <- seq(from = max.r + 1,
                to = (N + 1) %/% 2,
                by = 1)
} else {
  Ls_ssa <- seq(from = max.r + 1,
                to = (N + 1) %/% 2,
                by = 5)
}

groups_hossa <- list(1:max.r)
trunc_dims <- list(1:3)

# I >= L >= J
if (n_case == "") {
  Is_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 1)
  Ls_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 1)
} else {
  Is_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 5)
  Ls_tmp <- seq(from = max.r + 1,
                to = N - max.r - 1,
                by = 5)
}
correct.dims <- which(outer(Is_tmp, Ls_tmp, (\(i, l) ifelse((i >= l) &
                                                      (N - i - l + 2 > max.r) &
                                                      (N - i - l + 2 <= l), TRUE, FALSE
))), arr.ind = TRUE)

len.out <- nrow(correct.dims)

tens.dims <- matrix(ncol = 3, nrow = len.out)
colnames(tens.dims) <- c("I", "L", "J")
tens.dims[, "I"] <- Is_tmp[correct.dims[, 1]]
tens.dims[, "L"] <- Ls_tmp[correct.dims[, 2]]
tens.dims[, "J"] <- N - tens.dims[, "I"] - tens.dims[, "L"] + 2

tens.dims <- tens.dims[order(tens.dims[, 1], tens.dims[, 2], decreasing = TRUE), ]
tens.dims_list <- apply(tens.dims, 1, \(v) v[1:2], simplify = list)


sds <- seq(0, 0.6, by = 0.2)

params_grid_ssa <- list(sd = sds, L_ssa = Ls_ssa)
params_grid_hossa <- list(sd = sds,
                          td_hossa =  trunc_dims,
                          L_hossa = tens.dims_list)
}
```

```{r}
R <- 500

# if (is.matrix(signal)) {
#   ssa_err <- calc_errors_by_params(params_grid_ssa, R, pred_mssa_rec, rmse_ts_nd, signal, seed = 5)
#   tmssa_method <- "HOOI"
#   tssa_err <- calc_errors_by_params(params_grid_hossa, R, pred_homssa_rec, rmse_ts_nd, signal, seed = 5)
#   save(ssa_err, tssa_err, file = paste0("./Research/comp_results/point_wise_errors/", S_case, "_mv", full_case, ".RData"))
# } else {
params_grid_ssa <- list(sd = 5, L_ssa = c(12, 24, 30, 36))
params_grid_hossa <- list(sd = 5,
                          td_hossa =  trunc_dims,
                          L_hossa = list(c(12, 49), c(12, 37), c(7, 36), c(12, 31), c(19, 30), c(24, 25)))
  ssa_err <- calc_errors_by_params(params_grid_ssa, R, pred_ssa_rec, rmse_ts_nd, signal, seed = 5)
  tssa_err <- calc_errors_by_params(params_grid_hossa, R, pred_hossa_rec, rmse_ts_nd, signal, seed = 5)
#   R <- 500
#   sd <- 0.6
#   L_ssa <- ssa_err |> filter(sd == 0.6) |> filter(error == min(error)) |> getElement("L_ssa")
#   td_hossa <- trunc_dims
#   L_hossa <- tssa_err |> filter(sd == 0.6) |> filter(error == min(error)) |> getElement("L_hossa")
#   ssa_err_pw <- (\() {
#     q <- progressor(R)
#     calc_errors(R, pred_ssa_rec, rmse_ts_pw, signal, q, seed = 5)
#   })()
#   tssa_err_pw <- (\() {
#     q <- progressor(R)
#     calc_errors(R, pred_hossa_rec, rmse_ts_pw, signal, q, seed = 5)
#   })()
# save(ssa_err, tssa_err, ssa_err_pw, tssa_err_pw, file = paste0(rprojroot::find_rstudio_root_file(), "/Research/comp_results/point_wise_errors/", S_case, full_case, ".RData"))
# }
```

```{r}
rbind(data.frame(rmse = ssa_err_pw, method = "SSA", x = 1:N),
      data.frame(rmse = tssa_err_pw, method = "HO-SSA", x = 1:N)) |>
  ggplot() + geom_line(aes(x = x, y = rmse, color = method)) +
  annotate("label", x = N / 4, y = max(ssa_err_pw) * 0.97, label = sprintf("SSA: L = %d\nHO-SSA: L = (%d, %d)", L_ssa, L_hossa[[1]][1], L_hossa[[1]][2])) + theme_minimal()
```

```{r}
summarise_errors(rename(ssa_err, L = L_ssa))
```

```{r}
summarise_errors(rename(tssa_err, L = L_hossa))
```


```{r}
# Code to check that column spaces are correct
# all(apply(as.matrix(attributes(st)$unfolds_r[[3]]), 2, \(v) any(apply(rs_unfold(st, 3)@data, 2, \(v2) all(v - v2 < 1e-8)))))
# [1] TRUE
# all(apply(rs_unfold(st, 3)@data, 2, \(v) any(apply(as.matrix(attributes(st)$unfolds_r[[3]]), 2, \(v2) all(v - v2 < 1e-8)))))
```

